# -*- coding: utf-8 -*-
# Spanish quest translations aligned by INDEX to data.js order.
ES = [
("Construir un lecho Hugelkultur", "Construye un montículo hugelkultur pequeño con mantillo, semillas y plantas fijadoras de nitrógeno."),
("Cortar y soltar", "Poda las plantas y deja el material en su lugar como mantillo sobre una zona del jardín."),
("Compostaje estilo Ruth Stout", "Prepara zonas del jardín con mantillo grueso usando capas orgánicas y restos de cocina."),
("Guardar semillas", "Cosecha, seca y guarda semillas de cuatro especies de plantas diferentes."),
("Construir un hugelkultur de 12 pies", "Extiende un lecho hugelkultur hasta unos 12 pies con troncos, mantillo y tierra."),
("Fomentar plantas voluntarias", "Identifica y protege cinco plantas que brotaron solas en el jardín."),
("Sembrar perennes directamente", "Siembra cultivos perennes en el suelo y registra lo que va brotando."),
("Hacer un jardín de policultivo de 100 pies cuadrados", "Diseña y planta un jardín de especies mixtas con al menos 12 especies."),
("Construir un hugelkultur de 7 x 24", "Crea un lecho hugelkultur más grande con troncos, mantillo y tierra."),
("Cultivar y cosechar 1M de calorías", "Planea, planta y cosecha un sistema de jardín que produzca un millón de calorías."),
("Crear un bosque de alimentos de un cuarto de acre", "Diseña y establece un bosque de alimentos diverso con varias capas."),
("Sembrar 50 de cada una de 10 especies perennes", "Planta grandes lotes de semillas de diez especies perennes y registra la germinación."),
("Cultivar y cosechar 4M de calorías", "Escala un sistema de cultivo para producir millones de calorías."),
("Construir un hugelkultur de 7 x 150", "Crea un sistema hugelkultur enorme con varios lechos y mantillo grueso."),
("Cosechar fruta de 12 árboles nacidos de semilla", "Cría y cosecha fruta de una docena de árboles que crecieron desde semilla."),
("Construir un bosque de alimentos de 1 acre", "Establece un bosque de alimentos de un acre completo con plantaciones en capas."),
("Guardar semillas de variedades locales", "Guarda semillas de 12 especies durante 3 generaciones y mantén sus rasgos fuertes."),
("Hacer 12 ladrillos de adobe", "Mezcla, moldea y seca un lote pequeño de ladrillos de adobe."),
("Hacer pintura de arcilla", "Mezcla y aplica un acabado simple de pintura de arcilla."),
("Nivelar con rocas una estructura deslizante", "Usa rocas para nivelar una estructura que se pueda mover sobre patines."),
("Hacer un techo de tablillas de 25 pies cuadrados", "Arma una sección pequeña de techo de tablillas."),
("Hacer encalado", "Mezcla y aplica un acabado de cal."),
("Evaluar mezclas de arcilla", "Prueba varias mezclas de arcilla, arena y paja y compara los resultados."),
("Construir un cobertizo pequeño sobre patines", "Enmarca y termina un cobertizo pequeño que pueda moverse sobre patines."),
("Hacer un lavabo de adobe", "Da forma y termina una pileta de adobe para una casa o cocina exterior."),
("Hacer un soporte para árbol", "Construye un soporte pequeño de materiales naturales para un árbol o un letrero."),
("Ventana funcional desde cero", "Construye desde cero un marco y un batiente de ventana funcionales."),
("Pared de paja de un wofati", "Crea una sección de pared de paja para una estructura estilo wofati."),
("Pared de zarzo y barro", "Teje un panel de zarzo y cúbrelo con yeso de arcilla."),
("Banco de adobe con techo de postes redondos", "Construye un banco y una cubierta de clima con materiales naturales."),
("Construir un wofati y vivir en él un invierno", "Crea una casa wofati y vive en ella durante las condiciones de invierno."),
("Tumbar un árbol seco de 6-8 pulgadas con serrucho de arco", "Tumba con seguridad un árbol seco pequeño de pie usando un serrucho de arco."),
("Tumbar un árbol seco de 6-8 pulgadas con motosierra", "Tumba con seguridad un árbol seco pequeño con motosierra y supervisión."),
("Tumbar un árbol vivo de 6-8 pulgadas con serrucho de arco", "Tumba con seguridad un árbol vivo pequeño usando un serrucho de arco."),
("Tumbar un árbol vivo de 6-8 pulgadas con motosierra", "Tumba con seguridad un árbol vivo pequeño con motosierra y supervisión."),
("Desramar 4 árboles", "Quita las ramas de cuatro árboles y apila la maleza ordenadamente."),
("Descortezar 2 árboles vivos y ponerlos a secar", "Pela dos árboles vivos y guárdalos separados del suelo para que se sequen."),
("Rajar y apilar madera seca de pie como leña", "Convierte la madera seca de pie en leña apilada."),
("Preparar 10 postes", "Prepara diez postes rectos para construir o cercar."),
("Hender 6 tablillas con un rompecal", "Parte seis tablillas de techo de madera de veta recta."),
("Construir 12 pies de cerca de postes o reparar 24 pies", "Construye o repara una sección de cerca de postes."),
("Tumbar al menos 12 árboles de 8 pulgadas o más", "Tumba con seguridad una docena de árboles medianos."),
("Una cuerda de leña cortada y apilada bajo techo", "Corta y apila una cuerda de leña donde se mantenga seca."),
("Hacer madera: una docena de 2x4s, 1x4s y 3/8x4s", "Asierra o cepilla un primer lote de madera."),
("Construcción con ramas: jaula de tomates de 5 pies y enrejado de frijol trepador de 8 pies", "Construye soportes para plantas con ramas y postes."),
("Cerca de postes de 36 pies más puerta con pestillo", "Construye una cerca de postes más larga con una puerta que funcione."),
("Sembrar semillas de árbol para 100 pies de cerca viva", "Siembra semillas de árbol para una cerca viva futura y registra la germinación."),
("Poner tres cuerdas de leña", "Corta, raja y apila tres cuerdas de leña."),
("Hacer madera: ocho docenas de 2x4s, 1x4s y 3/8x4s", "Produce un gran lote de madera aserrada."),
("Construir seis gatos de roca con troncos partidos", "Haz gatos de roca resistentes para levantar o sostener."),
("Cerca de postes de 120 pies con buena puerta y pestillo", "Construye una cerca de postes larga con una puerta sólida."),
("Sembrar 300 semillas de acacia negra", "Siembra semillas de acacia negra a escala y registra la germinación."),
("Sembrar 300 gallitos", "Empieza un parche de gallitos y observa cómo se propaga."),
("Sembrar 300 ortigas", "Empieza un parche de ortigas y manéjalo con seguridad."),
("Sembrar 60 sauces", "Cultiva sauces para futura comida, cercos y cestería."),
("Sembrar 40 arces plateados de savia dulce", "Establece árboles que puedan dar savia y sombra."),
("Sembrar 10 cedros", "Establece una línea de cedros para refugio y hábitat futuros."),
("Construcción con ramas: seis jaulas de tomate de 5 pies y tres enrejados de 8 pies", "Construye un conjunto completo de soportes de jardín con postes y ramas."),
("Sembrar semillas de árbol para 800 pies de cerca viva", "Siembra semillas para una cerca viva larga en el futuro."),
("Poner 50 pies de seto vivo", "Construye un seto vivo y protégelo hasta que se establezca."),
("Cobertizo de tierra 8x8x8 con alero de 5 pies", "Construye un cobertizo de tierra que cumpla las medidas indicadas."),
("Palo para izar: levantar un tronco de 10 pies a 15 pies", "Usa un palo para izar para elevar un tronco con seguridad."),
("Hongos al aire libre: 1 libra de ostra y shiitake cada una", "Cultiva hongos ostra y shiitake al aire libre."),
("Poner seis cuerdas de leña", "Produce y apila seis cuerdas de leña."),
("200 maderas 2x4s, 1x4s y 3/8x4s", "Haz una pila muy grande de madera aserrada."),
("Construir 24 gatos de roca con troncos partidos", "Haz un juego resistente de gatos de roca."),
("Sembrar semillas para restaurar el lecho de un arroyo", "Siembra y estabiliza una zona grande de restauración de lecho de arroyo."),
("Cobertizo de tierra: 3 celdas, 12x12x12 cada una, aleros de 5 pies", "Construye un cobertizo de tierra de varias celdas a gran escala."),
("Construir dos estructuras deslizables", "Crea dos estructuras que puedan moverse sobre patines."),
("Palo para: levantar un tronco de 20 pies a 20 pies", "Levanta un tronco grande con un sistema de palo para izar."),
("Producir 10 libras de ostra y shiitake", "Cultiva una gran cosecha de hongos al aire libre."),
("Tallar una cuchara", "Da forma a una cuchara de madera útil a partir de una rama o madera de desecho."),
("Hacer un mazo de madera", "Convierte un palo o rama redonda en un mazo simple."),
("Construir un banco simple de madera redonda", "Haz un banco pequeño y resistente con madera redonda y amarras."),
("Hacer percheros con ramas", "Crea un juego de percheros con ramas o ramitas."),
("Afilar un cuchillo", "Afila un cuchillo de cocina o de bolsillo con seguridad."),
("Afilar una pala o azada", "Restaura el filo de una herramienta para excavar."),
("Aceitar una herramienta", "Limpia y aceita una herramienta de mano para evitar la herrumbre."),
("Reparar una herramienta", "Arregla un mango, un ajuste o un tornillo de herramienta dañado."),
("Construir un terraplén", "Amontona y da forma a la tierra para hacer un terraplén pequeño."),
("Cavar una zanja de captación", "Corta una zanja poco profunda a nivel para frenar el agua."),
("Construir un sendero", "Crea un sendero simple que soporte el paso a pie."),
("Construir una casa para pájaros", "Haz una casita para pájaros con cortes limpios y armado firme."),
("Hacer un estante", "Construye y cuelga un estante simple."),
("Construir una caja de herramientas", "Construye una caja de herramientas útil con madera."),
("Hacer un taburete", "Construye un taburete pequeño con ensambles firmes."),
("Cocinar una comida en estufa cohete", "Prepara comida en una estufa cohete simple o en un campamento."),
("Construir una estufa cohete pequeña", "Arma una estufa cohete básica para cocinar."),
("Hacer un modelo de estufa de masa cohete", "Construye un modelo pequeño que muestre cómo funciona una estufa de masa cohete."),
("Calentar agua con una estufa cohete", "Usa un sistema cohete para calentar agua para una tarea."),
("Cocinar un grano de 4 maneras", "Prepara un grano de cuatro maneras diferentes."),
("Conservar un alimento", "Conserva un alimento congelándolo, secándolo, fermentándolo o enlatándolo."),
("Pan desde cero", "Hornea pan con harina, agua, levadura o masa madre y sal."),
("Cocinar con caja de paja", "Cocina una comida en una caja de paja o en una olla aislante."),
("Construir un comedero o bebedero para pájaros", "Haz un comedero o fuente de agua para aves o polinizadores."),
("Crear un parche de hábitat para polinizadores", "Planta y protege un parche que sustente abejas y mariposas."),
("Limpiar un refugio o gallinero de animales", "Limpia y acondiciona un refugio o gallinero sencillo."),
("Construir un refugio para la fauna", "Haz un refugio pequeño o una pila de ramas para la fauna local."),
("Identificar 5 plantas silvestres comestibles", "Aprende a reconocer cinco plantas silvestres comestibles de tu zona."),
("Cosechar un alimento silvestre", "Recoge bayas, frutas, frutos secos o verduras con permiso y cuidado."),
("Hacer un té silvestre", "Seca o deja reposar una planta silvestre segura para hacer té."),
("Conservar una cosecha silvestre", "Seca, congela o conserva de otra forma algo recolectado."),
("Cocinar para un vecino o un grupo", "Prepara comida para alguien fuera de tu hogar."),
("Arte público", "Crea una obra de arte pensada para alegrar un espacio compartido."),
("Dar un taller o intercambio de habilidades", "Enseña u organiza una clase simple para otros."),
("Organizar un intercambio", "Coordina un intercambio de bienes, semillas o habilidades."),
("Remendar un agujero", "Repara un agujero en una tela con una puntada o un parche simple."),
("Cambiar un botón", "Cose un botón de nuevo o reemplaza uno que falte."),
("Hacer un dobladillo a una prenda", "Acorta o remata el dobladillo de una prenda."),
("Cocer un objeto", "Haz un objeto pequeño cosido como una bolsita, servilleta o bolso."),
("Usar jabón seguro para aguas grises", "Elige un jabón que sea seguro para el uso de aguas grises."),
("Reutilizar el agua de enjuague en un lecho de plantas", "Lleva el agua de enjuague a una cuenca de mantillo o a un lecho de plantas."),
("Acolchar una cuenca de sauces", "Añade mantillo alrededor de una zona de sauce o de álamo."),
("Plantar un esqueje de sauce o de álamo", "Inicia un esqueje de sauce o de álamo para el futuro uso de aguas grises."),
("Martillar y doblar un gancho de metal", "Da forma a un gancho simple a partir de una pieza plana o redonda."),
("Limar y suavizar un borde de metal", "Usa una lima para terminar y suavizar una pieza de metal."),
("Cortar material simple con una sierra de arco", "Corta metal con seguridad con herramientas de mano."),
("Hacer un soporte o colgador pequeño", "Crea un soporte, colgador o sujetador útil de metal."),
("Cambiar una arandela de grifo", "Arregla una gotera cambiando la arandela del grifo."),
("Desatascar un desagüe", "Despeja un desagüe de lavabo o ducha con una herramienta o método simple."),
("Arreglar una conexión de manguera que gotea", "Detén una fuga en una manguera o en una conexión de agua exterior."),
("Aislar una tubería de agua caliente", "Envuelve una tubería o línea de agua caliente para conservar el calor."),
("Construir un circuito de batería y foco", "Haz un circuito simple que funcione con una batería y una luz."),
("Cambiar un foco con seguridad", "Cambia un foco y comprueba que el artefacto funciona."),
("Organizar y etiquetar los cables", "Ordena los cables y etiquétalos para que sea más fácil y seguro usarlos."),
("Probar una batería y leer el voltaje", "Mide o compara el voltaje de una batería y anota el resultado."),
("Vender o intercambiar algo hecho en casa", "Haz algo e intercámbialo o véndelo a otra persona."),
("Llevar un presupuesto simple", "Anota los ingresos y gastos de una semana."),
("Ofrecer un servicio y registrar las ganancias", "Haz un trabajo pagado o intercambiado y anota lo que ganaste."),
("Crear un anuncio en línea pequeño", "Escribe un anuncio simple de algo que hiciste u ofreces."),
("Conocer una moneda extranjera", "Descubre una moneda, su símbolo y los países que la usan."),
("Hacer un cambio de moneda familiar", "Cambia algo de dinero de juguete entre dos monedas y calculen el total juntos."),
("Empezar un diario de operaciones de papel", "Anota una operación imaginaria: lo que esperabas contra lo que pasó de verdad."),
("Comparar el poder de compra", "Pregunta cuánto cuesta un artículo común en dólares, euros y francos."),
("Ahorrar para una meta pequeña", "Guarda un poco de dinero de bolsillo para una meta pequeña durante un mes y hazle seguimiento."),
("Seguir los tipos de cambio durante una semana", "Observa un par de monedas durante una semana y anota si sube, baja o se mantiene."),
("Hacer una operación simulada", "Usa un simulador gratuito: haz una operación de papel con un límite de pérdida y registra el resultado."),
("Planear un experimento para salir del dólar", "Diseña una forma pequeña en que tu familia pueda intercambiar valor más allá del dólar."),
("Organizar la noche familiar del juego de divisas", "Reúne a la familia en un simulador gratuito y corran una noche de misión."),
("Presentar un plan familiar de libertad financiera", "Expón el plan familiar para ahorrar, intercambiar y hacer crecer el valor a su manera."),
("Hacer una temporada simulada", "Lleva un portafolio imaginario de varias monedas durante una temporada completa y anota cada decisión."),
("Mantener viva la regla de oro", "Enseña a un amigo o hermano: primero protege el dinero, segundo aprende, tercero invierte."),
("Identificar 5 hierbas medicinales", "Aprende a reconocer cinco hierbas medicinales o plantas curativas comunes."),
("Hacer un té de hierbas simple", "Seca o deja reposar una hierba segura para hacer té."),
("Preparar un ungüento o bálsamo", "Haz un ungüento, bálsamo o barra de loción simple."),
("Armar una tarjeta familiar de hierbas de primeros auxilios", "Anota algunas hierbas y para qué se usan."),
("Lavar los platos sin lavavajillas", "Lava los platos a mano y guárdalos limpios."),
("Limpiar un plato grasoso sin jabón", "Quita la grasa de un plato con un método de bajos químicos."),
("Lavar la ropa a mano", "Lava la ropa sin lavadora."),
("Hacer trapos con ropa vieja", "Convierte ropa gastada en trapos de limpieza útiles."),
("Probar las alarmas de humo y CO", "Revisa las alarmas de la casa y cambia las pilas si hace falta."),
("Practicar con un extintor", "Aprende a usar un extintor con seguridad."),
("Limpiar las canaletas con seguridad", "Quita los restos de las canaletas o bajantes."),
("Hacer una lista de suministros de emergencia", "Escribe una lista familiar de suministros de emergencia."),
("Construir un invento caprichoso con desechos", "Haz algo extraño, útil o divertido con materiales sobrantes."),
("Crear un marcador secreto de sendero familiar", "Diseña una señal o código oculto para un sendero o camino local."),
("Hacer música con objetos encontrados", "Crea un instrumento o un productor de sonido simple con basura o retazos."),
("Diseñar un juego o reto con presupuesto cero", "Inventa un juego, acertijo o reto familiar sin ningún presupuesto."),
("Ejercicios de los cinco animales", "Practica los ejercicios de los cinco animales como rutina de movimiento corporal."),
("Las ocho piezas de brocado", "Haz las ocho piezas de brocado como una serie de ejercicios suaves."),
("Las doce vigilias del zodiaco", "Practica la serie de movimientos de las doce vigilias del zodiaco."),
("Ejercicios del ciervo y la grulla", "Haz los ejercicios del ciervo y la grulla para el equilibrio y la coordinación."),
("Cocinar para un grupo", "Prepara comida para un grupo y limpia después."),
("Arte público", "Crea arte que se pueda compartir con el público."),
("Dar un taller", "Enseña una clase simple o un intercambio de habilidades."),
("Organizar un intercambio", "Coordina un intercambio de bienes o habilidades útiles."),
]
