# French translations for _build_translations.py
FR_SUBJECTS = {
    "Science": "Sciences",
    "Math": "Mathématiques",
    "Art": "Arts",
    "PE": "Éducation Physique",
    "Health": "Santé",
    "Geography": "Géographie",
    "Writing": "Écriture",
    "History": "Histoire",
    "Economics": "Économie",
    "Constitution": "Constitution",
    "Reading": "Lecture",
}

FR_ROLES = {
    "Tracker": "Traqueur / Traqueuse",
    "Witness": "Témoin",
    "Hearth Tender": "Gardien du Foyer / Gardienne du Foyer",
    "Hearth": "Foyer",
    "Mentor": "Mentor / Mentore",
    "Mentors": "Mentors",
    "Trackers": "Traqueurs",
    "Witnesses": "Témoins",
}

FR_TIERS = {
    "Sand": "Sable",
    "Straw": "Paille",
    "Wood": "Bois",
    "Iron": "Fer",
}

FR_UI = {
    # nav
    "Setup": "Configuration",
    "Village": "Village",
    "Studio": "Studio",
    "Quests": "Quêtes",
    "Schoolhouse": "École",
    "Library": "Bibliothèque",
    "Mentor's Circle": "Cercle du Mentor",
    "Circle": "Cercle",
    "Commons": "Plaza",
    # title screen
    "WELCOME": "BIENVENUE",
    "The Village — A Roll Making Game (RMG) for families": "Le Village — Un Jeu de Formation des Rôles (RMG) pour familles",
    "A real-life skill-building journey — not a digital game you play on a screen. Build real skills, grow real attributes, earn real badges in the real world.": "Un parcours réel de développement de compétences — pas un jeu numérique sur écran. Développe de vraies compétences, éprouve de vrais progrès, gagne de vrais badges dans le monde réel.",
    "Data.js not found or failed to load. Using fallback data.": "data.js introuvable ou impossible à charger. Utilisation des données de secours.",
    "▼ Scroll down ▼": "▼ Faites défiler ▼",
    # setup screen
    "School days already completed": "Jours d'école déjà effectués",
    "Total hours already logged": "Heures totales déjà enregistrées",
    "Current curriculum (optional)": "Programme actuel (facultatif)",
    "Player Name": "Nom du joueur",
    "Save & Enter Village": "Enregistrer et entrer au Village",
    "Reset Village": "Réinitialiser le Village",
    "Reset": "Réinitialiser",
    "8. Start Over / Reset": "8. Recommencer / Réinitialiser",
    "Wipe all progress, quests, attendance, and player data from this browser and start fresh. Cannot be undone.": "Efface tous les progrès, quêtes, présences et données de joueurs de ce navigateur et repartez à zéro. Impossible d'annuler.",
    # village
    "Your Family Guild": "Le Groupe de Votre Famille",
    "Click a character to open the Avatar Studio": "Cliquez sur un personnage pour ouvrir le Studio d'Avatar",
    "Save Village (Download File)": "Enregistrer le Village (télécharger le fichier)",
    "Load Saved Village": "Charger le Village enregistré",
    "Start Questing": "Commencer les Quêtes",
    # studio
    "Avatar Studio": "Studio d'Avatar",
    "Class": "Classe",
    "Face": "Visage",
    "Hair": "Cheveux",
    "Outfit": "Tenue",
    "Gear": "Équipement",
    "Background": "Arrière-plan",
    "Wardrobe": "Garde-robe",
    "Attributes": "Attributs",
    "Save & Exit to Village": "Enregistrer et quitter vers le Village",
    # quest board
    "The Quest Board": "Le Tableau des Quêtes",
    "All Quests": "Toutes les quêtes",
    "My Biome Only": "Mon biome uniquement",
    "Badge Progression": "Progression des Badges",
    "Free Roam — all quests unlocked": "Mode Libre — toutes les quêtes débloquées",
    "Adventure Mode — complete 50% of a tier within one guild to unlock the next": "Mode Aventure — terminez 50% d'un niveau dans une guilde pour débloquer le suivant",
    "Story Mode — a guided adventure, new every time": "Mode Histoire — une aventure guidée, nouvelle à chaque fois",
    "Survival Mode — train the family for the long haul": "Mode Survie — entraînez la famille pour le long terme",
    "Official Permies PEP Quests": "Quêtes PEP Officielles de Permies",
    "Submit evidence to their forum for official certification.": "Envoyez vos preuves sur leur forum pour une certification officielle.",
    "Holistic RPG Add-on Guilds": "Guildes Bonus RPG Holistiques",
    "Custom to The Village. Do not count toward official Permies PEP certification.": "Spécifiques au Village. Ne comptent pas pour la certification officielle PEP de Permies.",
    "Guild": "Guilde",
    "No description available.": "Aucune description disponible.",
    "complete": "terminées",
    "Locked": "Verrouillée",
    "Post to Permies": "Publier sur Permies",
    "Complete!": "Terminée !",
    "Finalize": "Finaliser",
    "Learn More": "En savoir plus",
    # roster
    "Trackers": "Traqueurs",
    "Witnesses": "Témoins",
    "Otis Verification Protocol:": "Protocole de Vérification Otis :",
    "photo of materials/site": "photo des matériaux / du lieu",
    "photo of you working": "photo de vous en train de travailler",
    "photo of finished product WITH a sign showing your name and date": "photo du produit fini AVEC une pancarte indiquant votre nom et la date",
    "Select who participated. Multiple people can hold the same role!": "Sélectionnez qui a participé. Plusieurs personnes peuvent tenir le même rôle !",
    "Confirm & Complete Quest": "Confirmer et terminer la quête",
    "Guided Path for this Quest": "Parcours guidé pour cette quête",
    "Prep": "Préparation",
    "Core": "Cœur",
    "Stretch": "Défi",
    "Curriculum topics connected to this skill:": "Sujets de programme liés à cette compétence :",
    "Skill-wide resources:": "Ressources générales de la compétence :",
    "Feeling lucky? Spin for a surprise resource:": "Tentez votre chance ? Faites tourner pour une ressource surprise :",
    "Spin": "Tourner",
    # schoolhouse
    "The Colorado Schoolhouse": "L'École du Colorado",
    "Attendance Tracker (CO Law: 172 Days)": "Suivi de Présence (Loi du CO : 172 jours)",
    "Days Completed:": "Jours effectués :",
    "Hours Logged:": "Heures enregistrées :",
    "hrs": "h",
    "Log 4-Hour School Day": "Enregistrer une journée d'école de 4 heures",
    "Log 1-Hour Day": "Enregistrer une journée d'1 heure",
    "Academic Transcript (CO Required Subjects)": "Relevé Académique (Matières obligatoires du CO)",
    "Hours are logged from completed quests (2 hrs each) plus any custom hours below.": "Les heures sont enregistrées à partir des quêtes terminées (2 h chacune) plus toutes heures personnalisées ci-dessous.",
    "Log Custom Academic Hours": "Enregistrer des heures académiques personnalisées",
    "Add Hours": "Ajouter des heures",
    "Bring Your History": "Apportez votre historique",
    "Already partway through your school year with another curriculum? Add your prior days and hours here so the tracker reflects where you actually are.": "Déjà à mi-chemin de votre année scolaire avec un autre programme ? Ajoutez vos jours et heures précédents ici pour que le suivi reflète votre situation réelle.",
    "Add History to Tracker": "Ajouter l'historique au suivi",
    "Hours": "heures",
    # library
    "The Village Library": "La Bibliothèque du Village",
    "A curated knowledge graph of free, public domain, and government resources for holistic homeschooling.": "Un graphe de connaissances organisé de ressources gratuites, de domaine public et gouvernementales pour l'école à la maison holistique.",
    "Educational Philosophy & Nature Connection": "Philosophie Éducative & Connexion à la Nature",
    "Colorado Homeschooling": "École à la Maison au Colorado",
    "Permies & PEP Badges": "Badges Permies & PEP",
    "Curriculum by Subject": "Programme par Matière",
    "The Money Lab — Financial Literacy & Foreign Exchange": "Le Laboratoire de l'Argent — Culture Financière & Change de Devises",
    # commons
    "The Village Commons": "La Plaza du Village",
    "Family Achievements": "Réussites Familiales",
    "Bridge to Permies": "Pont vers Permies",
    "Post your evidence to the PEP Forum to get officially certified by Paul Wheaton's team.": "Publiez vos preuves sur le Forum PEP pour obtenir la certification officielle de l'équipe de Paul Wheaton.",
    "Official PEP quests (marked with the shield icon) count toward Permies certification. RPG Add-on quests (marked with the sparkle icon) are custom to The Village and do not count toward official PEP badges.": "Les quêtes PEP officielles (avec l'icône bouclier) comptent pour la certification Permies. Les quêtes bonus RPG (avec l'icône étincelle) sont spécifiques au Village et ne comptent pas pour les badges PEP officiels.",
    "Open PEP Forum": "Ouvrir le Forum PEP",
    "How to Apply for a Badge": "Comment demander un badge",
    "Optional: The Offline Archive": "Facultatif : L'Archive Hors Ligne",
    "For families wanting a complete offline backup drive, download these open-source collections to a local hard drive:": "Pour les familles souhaitant une sauvegarde complète hors ligne, téléchargez ces collections open-source sur un disque local :",
    "Quests Done": "Quêtes terminées",
    "Wardrobe Items": "Objets de garde-robe",
    "Sand Badges": "Badges de Sable",
    "Straw Badges": "Badges de Paille",
    "Wood Badges": "Badges de Bois",
    "Iron Badges": "Badges de Fer",
    "Earned": "Gagné(e)",
    "Family Members": "Membres de la famille",
    "School Days": "Jours d'école",
    # circle
    "The 64 cultural elements of deep nature connection — from Jon Young's 512 Project and the 8 Shields framework. These practices weave the invisible fabric of community that makes permaculture skills sustainable across generations.": "Les 64 éléments culturels de la connexion profonde à la nature — du Projet 512 de Jon Young et du cadre des 8 Boucliers. Ces pratiques tissent le tissu invisible de la communauté qui rend les compétences en permaculture durables à travers les générations.",
    # gold modal
    "Gold Nugget Earned!": "Pépite d'Or gagnée !",
    "You worked the entire Commerce guild — budgets, currency exchange, paper trading, even a family forex night. That's real financial skill, earned in the real world.": "Vous avez travaillé toute la guilde du Commerce — budgets, change de devises, trading papier, même une soirée forex familiale. C'est une vraie compétence financière, gagnée dans le monde réel.",
    "The Gold Nugget is now part of your family's story. No real money was moved — only understanding.": "La Pépite d'Or fait désormais partie de l'histoire de votre famille. Aucun argent réel n'a été déplacé — seulement de la compréhension.",
    "Glow on ✨": "Brillez ✨",
    # otis / roster
    "Before": "Avant",
    "During": "Pendant",
    "After": "Après",
    # tiers / misc
    "Tier": "Niveau",
    "Level": "Niveau",
    "Guild of": "Guilde de",
    "Gold Nugget": "Pépite d'Or",
    "The Village — A Roll Making Game (RMG)": "Le Village — Un Jeu de Formation des Rôles (RMG)",
    # money lab print sheets
    "Print All 15 Sheets": "🖨️ Imprimer les 15 feuilles",
    "Print This Sheet": "🖨️ Imprimer cette feuille",
    "All 15 Sheets": "Les 15 feuilles",
    # village hub
    "Family Progress": "Progrès de la Famille",
    "quests completed": "quêtes terminées",
    "Quests:": "Quêtes :",
    "Wardrobe:": "Garde-robe :",
    "items": "objets",
    "earned": "gagné(e)",
    "Reward:": "Récompense :",
    # emoji-prefixed buttons (keys include the emoji, matching data-i18n)
    "💾 Save Village (Download File)": "💾 Enregistrer le Village (télécharger le fichier)",
    "📂 Load Saved Village": "📂 Charger le Village enregistré",
    "🔄 Reset": "🔄 Réinitialiser",
}

FR_GUILDS = {
    "Gardening": ("Jardinage", "Cultivez des aliments, conservez des graines et construisez des systèmes de jardin résilients."),
    "Natural Building": ("Construction Naturelle", "Utilisez l'argile, la paille, le bois et la pierre pour bâtir des abris sains."),
    "Woodland Care": ("Soin des Bois", "Entretenez les forêts, le bois de feu, les clôtures, les champignons et les systèmes de bois vivant."),
    "Round Wood Woodworking": ("Menuiserie de Bois Rond", "Construisez des objets utiles avec des rondins, bâtons et branches, avec peu de colle et de métal."),
    "Tool Care": ("Soin des Outils", "Gardez les outils affûtés, propres, huilés et réparés pour qu'ils durent plus longtemps."),
    "Earthworks": ("Terrassement", "Façonnez le terrain pour déplacer l'eau, réduire l'érosion et créer des chemins durables."),
    "Dimensional Lumber Woodworking": ("Menuiserie de Bois d'Œuvre", "Utilisez du bois droit et des assemblages solides pour fabriquer des meubles et structures pratiques."),
    "Rocket": ("Poêle Fusée", "Construisez des appareils à bois qui économisent le combustible et utilisent la chaleur avec une grande efficacité."),
    "Food Prep": ("Préparation des Aliments", "Conservez, cuisinez et savourez les aliments de façon sûre et délicieuse."),
    "Animal Care": ("Soin des Animaux", "Prenez soin des animaux domestiques et de ferme avec respect et abondance."),
    "Foraging": ("Cueillette Sauvage", "Apprenez à trouver, identifier et récolter des plantes sauvages comestibles en toute sécurité."),
    "Community Living": ("Vie en Communauté", "Pratiquez des compétences sociales, de service et d'événements qui aident les groupes à prospérer."),
    "Textiles": ("Textiles", "Fabriquez, réparez et utilisez le tissu, le fil et la fibre naturelle pour des choses utiles et belles."),
    "Greywater and Willow Feeders": ("Eaux Grises et Saules", "Gérez les eaux grises et cultivez des saules pour des jardins et paysages productifs."),
    "Metalworking": ("Travail du Métal", "Frappez, limez, soudez et assemblez le métal pour créer outils et structures."),
    "Plumbing and Hot Water": ("Plomberie et Eau Chaude", "Réparez les fuites, les drains et les systèmes d'eau et de chaleur de votre maison."),
    "Electricity": ("Électricité", "Apprenez les bases du courant alternatif et continu, des batteries, des circuits et du solaire en toute sécurité."),
    "Commerce": ("Commerce", "Gagnez de l'argent, échangez de la valeur, tenez des registres et apprenez comment les devises circulent — de la petite monnaie au coffre de la Pépite d'Or."),
    "Natural Medicine": ("Médecine Naturelle", "Apprenez des façons sûres et pratiques d'identifier et d'utiliser les plantes médicinales."),
    "Nest": ("Nid", "Gardez la maison propre, rangée et confortable pour la vie familiale de tous les jours."),
    "Homesteading": ("Autosuffisance", "Gérez des compétences pratiques qui maintiennent une maison et une famille prêtes pour de vraies urgences."),
    "Oddball": ("Curiosités", "Rassemblez des expériences de vie étranges, créatives et délicieusement inattendues."),
    "Vitality": ("Vitalité", "Développez la vitalité physique par le mouvement, le rythme et la conscience du corps."),
    "Community": ("Communauté", "Pratiquez des compétences sociales, de service et d'événements qui aident les groupes à prospérer."),
}
