/* Quest cards feed — auto-generated by build_village_quest_feed.py (living-library quest-queue). Do not edit by hand. */
const QUEST_CARDS = {
 "generated": "2026-09-25",
 "source": "living-library quest-queue (Engine of Practicality)",
 "note": "Auto-generated. A quest card is a TEST of a claim, not an endorsement. Proposed cards are visible here before merging into the Quest Board.",
 "benches": [
  {
   "id": "viktor-vortex",
   "name": "Viktor Vortex",
   "emoji": "🌀",
   "subtitle": "water, flow & Schauberger's legacy",
   "cards": [
    {
     "id": "2026-09-25-shared-well-yield-estimate",
     "date": "2026-09-25",
     "title": "Shared Well Yield Estimate Test",
     "emoji": "🔢",
     "guild": "Aetherforce — Community",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Finding the water is only half the decision — the other half is how much it gives. The dowsing tradition claims a sensitive person can put a number on a source's yield, and it even names the method. Test it with a tap, a jug and a stopwatch: a referee sets the flow out of sight, you write down your estimate in litres per minute, then the truth gets measured. Do it blind across a range of flows, on two days, with a non-dowser guessing alongside you. You get a rank correlation between what you said and what was true — a number that says whether your estimates carried any information at all. ⚡ Ae",
     "steps": "Set up a tap or valved hose whose flow a referee can change out of your sight and hearing (a lidded bucket or a corner works). First run the calibration arm: estimate the flow of a tap you can watch, whose true rate the referee has just measured and told you — if you can't produce a signal on a known flow, stop and record it as inconclusive, because the blind arm can't tell you anything. Then run 16 blind trials across two days: the referee sets one of four pre-registered rates (1, 2, 4, 8 L/min) from a shuffled list, you write your estimate in L/min before anything is revealed, and the referee then measures the truth with a jug and a stopwatch. Include 4 water-off trials you are not told about, and have a non-dowser estimate on the same trials as the control. Measurable outcome: Spearman rank correlation between your estimates and the true flows >= 0.6, with >=60% of estimates within +/-25% of truth and clearly better than the control, repeated in a second session — or an honest null at home scale. If you have your own spring, well or cistern, run the real-source arm too: estimate its yield blind, then measure it the same day.",
     "subjects": [
      "Science",
      "Measurement",
      "Community"
     ],
     "passFail": "PASS: blind Spearman rank correlation rho >= 0.6 between estimates and true flows AND >=60% of estimates within +/-25% of the true flow AND clearly better than the non-dowser control on both, repeated in a second session. FAIL: rho <= 0.2 (the estimates carry essentially no information about the flow) OR the operator is not better than the control - an honest negative (Skeptic's Star). INCONCLUSIV",
     "sourceNote": "sources/2026-09-25-scout-a-langs-1#find-1 (Saevarius manual, Ch. IX–X, Fr. Padey net-production method) + sources/2026-09-22-scout-a-langs-2#find-11 (UCR field record, 'Determinación del caudal que puede aportar el pozo')",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-24-wave-water-stress-recovery",
     "date": "2026-09-24",
     "title": "Wave-Water Stress-Recovery Test",
     "emoji": "🧠",
     "guild": "Aetherforce — Natural Medicine",
     "tier": "wood",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "A Japanese university team asked a sharp question: does water that has had a 'vibrational-wave' imprint transferred into it speed your recovery from mental stress? They put seven students through a 15-minute arithmetic stressor and measured the brain's alpha/beta ratio before and after. Three arms: no drink, plain water, imprinted water. The imprinted-water group recovered further than the no-drink group — and then the number that matters: PLAIN WATER landed almost as far, and was statistically indistinguishable from both. So the published result never separated the imprint from the water. Thi",
     "steps": "You need a consumer EEG headset that reports alpha (8-13 Hz) and beta (13-30 Hz) band power (~$100-400 — this is the queue's first card that needs a purchased instrument), a printed sheet of one-digit addition problems, a timer, a coil of magnet wire around a 2 L glass jar driven at 7.8 Hz from a BATTERY-powered source (never mains), two identical opaque bottles, and a third person as coder. PRE-REGISTER at least 6 sessions per arm (18 total, one per day) before you start. Each session: 5 min seated rest, 60 s eyes-closed EEG, 15 min of timed one-digit addition, then 2 min drinking 150 mL within the 2 minutes (or sitting quietly for the no-drink arm), then 60 s eyes-closed EEG; analyse the 10-40 s window exactly as the source did. Three arms, randomized from a schedule drawn before session one, blinded so neither subject nor analyst knows the code: IMPRINTED (coil energized 30 min at 7.8 Hz), PLAIN (same jar, same 30-min wait, coil NOT energized), NOTHING (empty coded bottle). First check the assay itself: the alpha/beta ratio must FALL across the stressor in the no-drink arm — if it doesn't, the run is void, not a refutation. Measurable outcome: per-session RECOVERY RATIO = post-s",
     "subjects": [
      "Science",
      "Measurement",
      "Health"
     ],
     "passFail": "PASS: imprinted-arm mean recovery ratio significantly greater than the PLAIN-water arm (within-subject Wilcoxon signed-rank, pre-registered N, alpha 0.05) AND the no-drink arm shows the expected stress-induced alpha/beta drop (assay valid) AND the direction repeats in a second block of sessions | FAIL: imprinted about equal to plain water (the effect, if any, is the water, not the imprint) — hones",
     "sourceNote": "sources/2026-09-16-scout-a-de-fr-ja.md (find #10) — primary: 江川陽介 (Egawa Yōsuke), 「振動波エネルギーを転写した水（波動水）は精神的ストレス負荷からの回復に影響をあたえるか」, Kokushikan University graduate-school research bulletin, JSPS Kakenhi 16K01669, https://www.kokushikan.ac.jp/gs/department/hs/docs/01_102.pdf",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-23-blind-water-line-location",
     "date": "2026-09-23",
     "title": "Blind Water-Line Location Test",
     "emoji": "💧",
     "guild": "Aetherforce — Earthworks",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Before a community digs a shared well, someone has to say where the water is. The dowsing tradition says a sensitive person can find the line and even tell which way the water runs. Bury a garden hose in a zigzag, have a referee flip a coin to decide which end the water enters from, and walk it blind. Mark where you think the line is; say which way the water flows before the coin is revealed. A second person who claims no skill walks the same field as the control. You get a number against ground truth — and either way, you learn what the claim is worth at home scale. ⚡ Aetherforce custom: does",
     "steps": "Lay a 15–30 m garden hose in a gentle zigzag, cover it with soil or a board, and record the true path with stakes you then hide. A referee flips a coin to decide which end the water enters from, connects it out of sight, and starts the flow. You walk the field with rods and mark at least five points where you think the line runs — each measured as a perpendicular distance from the true line — then state the flow direction in writing before the coin is revealed. Run 20 direction trials, 10 static (water off) trials you are not told about, and have a non-dowser run the same direction trials as the control. Measurable outcome: blind direction hit rate over 20 trials against a 50% chance baseline (binomial), your median location error in metres versus the control operator's, and your false-positive rate on the static trials. Target: >=15/20 direction hits at p<0.05 AND median location error <1.0 m and at least half the control's AND <=2/10 static false positives, repeated in a second session — or an honest refutation at home scale.",
     "subjects": [
      "Science",
      "Observation",
      "Community"
     ],
     "passFail": "PASS: blind direction hit rate >=15/20 (binomial p<0.05 one-tailed, chance 0.5) AND operator median location error <1.0 m and at least half the control operator's error AND static-trial false positives <=2/10, and the direction result repeats in a second session. FAIL: operator median location error at or above the control operator's AND blind direction hit rate within chance (7-13/20, p>0.05) - a",
     "sourceNote": "sources/2026-09-21-scout-b-langs-1#entries-1-3 (Balck artificial water veins; Stängle 1972 scintillation measurements) + sources/2026-09-22-scout-a-langs-2#find-11 (UCR field record)",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-23-contour-swale-retention",
     "date": "2026-09-23",
     "title": "Contour Swale Rain-Retention Test",
     "emoji": "🌧️",
     "guild": "Aetherforce — Greywater & Willow",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "When rain lands on bare ground it runs off, and the water table falls. The Schauberger-to-permaculture lineage says the fix is to keep the rain where it falls — dig a swale on contour and let the soil drink. This is a test of that on YOUR slope: three small plots side by side — one untouched, one with a meandering contour swale, one with a straight ditch of the same volume — and one wet season of measuring how much water each one sheds. You get your own numbers for how much rain your ground keeps, and an answer to a sharper question: does the SHAPE of the earthwork matter, or only its volume? ",
     "steps": "Mark three adjacent plots on one slope — Control (untouched), Swale (a meandering ditch on contour, ~2–3 m long, 0.3 m deep, bermed downhill, no liner), and Ditch (a straight trench of the SAME excavated volume). Before digging, run a can-infiltration test at three points per plot (drive a bottomless tin can 5 cm in, pour 250 mL, time it) and record soil moisture at 15 and 30 cm. Install a runoff collector at the downslope edge of each plot. After each rain of ≥5 mm, record rainfall depth, runoff litres per plot, and how many hours the swale and ditch hold standing water. Re-run the infiltration test after four weeks. Measurable outcome: runoff litres per mm of rain for Swale and Ditch versus Control across ≥5 comparable events; infiltration time before vs after; water-holding hours after a ≥10 mm rain; downslope soil moisture at 30 cm. Target: Swale runoff <50% of Control AND Swale infiltration ≥2× its own baseline and faster than Control AND swale holds water ≥6 h after a ≥10 mm rain AND downslope 30 cm moisture above Control's — repeated in a second month; plus, at equal volume, Swale holding water ≥1.5× longer than the straight Ditch — or an honest negative at home scale.",
     "subjects": [
      "Science",
      "Observation",
      "Earth Care"
     ],
     "passFail": "PASS (retention): over >=5 comparable rain events, Swale-plot runoff <50% of Control-plot runoff AND Swale post-build infiltration time >=2x its own pre-build baseline and faster than Control AND the Swale holds water >=6 h after a >=10 mm rain AND downslope 30 cm moisture is higher than Control's - and the runoff result repeats in a second month. PASS (form): at equal excavated volume, the Swale ",
     "sourceNote": "translations/2026-09-18-el-secreto-del-agua-tamera-es-en (Bernd Walter Mueller, 'El Secreto del Agua como Base para una Nueva Tierra', Tamera 2011) + sources/2026-09-18-scout-a-langs-1#find-3",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-21-vortex-motor-mvp",
     "date": "2026-09-21",
     "title": "The Vortex Motor Energy Balance",
     "emoji": "🌀",
     "guild": "Aetherforce — Water",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Viktor Schauberger spent his life arguing that nature builds with implosion — the inward, cooling, ordering vortex — not explosion, and that a vortex of water holds energy we throw away. In November 2025 a Spanish engineer published an open-source build challenge that puts that claim on a workbench: for under 50 euros, using common materials, build a small water vortex in a resonant cavity and use it to light an LED. He published the plans, the materials list, and a step-by-step guide — and he was honest that it is a challenge, not a result. So here is the quest, and it is a good one precisely",
     "steps": "Obtain the open-source build doc (Zenodo DOI 10.5281/zenodo.17635970) and build the MVP Vortex Motor to its specification — cavity, rotor, turbine, circuit — photographing each stage. Then instrument it honestly: measure the energy GOING IN (if gravity-fed, flow rate in litres per minute and usable head in metres, so P_in = ρ·g·Q·h; if pumped, the pump's wall power with a plug-in meter) and the energy COMING OUT (voltage and current at the LED/load). Run at least 3 timed runs of 10+ minutes on different days, record every number, and compare. Measurable outcome: P_out > P_in in every run, by more than measurement uncertainty = a genuine anomaly worth reporting to the world; P_out ≤ P_in in every run = ordinary turbine generation and the over-unity claim is retired honestly. Note in your write-up that 'the LED lights' alone proves nothing — only the balance does.",
     "subjects": [
      "Science",
      "Engineering",
      "Self-Reliance"
     ],
     "passFail": "PASS: P_out > P_in in every run (≥ 3 runs, ≥ 10 min each, on different days), margin larger than combined measurement uncertainty — a genuine over-unity anomaly, report raw numbers and seek independent replication | FAIL: P_out ≤ P_in in every run — ordinary turbine generation; the over-unity claim is retired honestly (Skeptic's Star) | INCONCLUSIVE: fewer than 3 runs, input or output not measured",
     "sourceNote": "translations/2026-09-11-vortex-motor-negentropic-propulsion-es.md — 'El Motor de Vórtice: Hacia una Tecnología de Propulsión Negentrópica Basada en la Dinámica de Implosión del Éter,' the companion theoretical paper (Zenodo 10.5281/zenodo.17626722, 2025-11-17, CC BY 4.0). Build doc: Zenodo 10.5281/z",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-20-water-memory-imprint",
     "date": "2026-09-20",
     "title": "Water Memory Imprint Test",
     "emoji": "❄️",
     "guild": "Aetherforce — Natural Medicine",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural",
      "homestead"
     ],
     "status": "proposed",
     "desc": "Water is the one thing in your house that everything living depends on, and it is the one thing nobody in your family has ever measured. The water-memory tradition says water keeps an imprint of what it has been exposed to — a spoken intention, a magnetic field, a substance long since diluted away — and that the imprint survives after the influence is gone. A Russian Academy of Sciences dissertation built a whole structural model on it; a Japanese researcher photographed ice crystals that supposedly changed shape with the words spoken over them; and the same article that describes the method a",
     "steps": "Pour from one bottle into twelve identical lidded glass jars. A family member who will not measure and will not send codes every jar and seals the key. Measure the noise floor first — ten repeated readings of one jar on the refractometer and the scale; that standard deviation is your threshold. Baseline all three hard endpoints on every jar. Then split the jars: half receive the influence (Arm A — a repeated spoken intention; Arm B — a separate run with half the jars inside a coil driven at 7.8 Hz for 30 minutes), and half are handled identically with no attempt. Re-measure all three endpoints, blinded to group. Freeze 0.5 mL from each jar at −25 °C, photograph the crystals, and score their symmetry blind with 2–3 raters against a rubric written down before the first photograph. Repeat three sessions on different days, re-coding each time, and unseal the key only after the numbers are written. Measurable outcome: the influenced group's mean change is ≥2× the measured noise floor on at least two of the three hard endpoints, consistent in at least two of three sessions, with the handled-only control showing no comparable shift = the imprint shows up in your kitchen; no difference, or",
     "subjects": [
      "Science",
      "Measurement",
      "Health"
     ],
     "passFail": "PASS: blinded mean change in the influenced group ≥2× the measured instrument noise floor on ≥2 of 3 hard endpoints (evaporation rate, refractive index, surface tension), direction consistent in ≥2 of 3 sessions, handled-only control showing no comparable shift, AND blind crystal scoring showing a consistent morphology difference with above-chance rater agreement | FAIL: no difference between infl",
     "sourceNote": "translations/2026-09-15-zenin-water-as-information-storage-ru.md — 'Water — Storage and Transmitter of Information,' the Russian account of S.V. Zenin's 1999 doctoral dissertation (Institute of Medical and Biological Problems, Russian Academy of Sciences) and of Masaru Emoto's crystal-photography me",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-18-piccardi-cosmic-precipitation",
     "date": "2026-09-18",
     "title": "Cosmic Precipitation Test",
     "emoji": "☀️",
     "guild": "Aetherforce — Plumbing & Hot Water",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural",
      "homestead"
     ],
     "status": "proposed",
     "desc": "Giorgio Piccardi was a professor of physical chemistry in Florence who spent twenty-one years doing the same small experiment every day. He added a hydrochloric solution of bismuth chloride to water — the two react and drop a white cloud of bismuth oxychloride — and set up ten beakers in open air next to ten identical beakers under a thin copper screen. Then he measured which beakers settled faster, called the result a percentage, and tracked it for two decades. His claim: the percentage is not stable, and not random. It moves with the sun's eleven-year cycle and with geomagnetic weather. The ",
     "steps": "Adult-handled acid work (gloves, eye protection, ventilated). Make one stock of dilute bismuth chloride solution and keep it consistent all run. Each session, fill twenty identical glasses with the same measured volume of the same water, dose each with the same measured volume of stock in the same order, and time from the last pour. An adult labels the glasses and randomly assigns ten to a thin copper screen and ten to open air, sealing the assignment; the person reading results must not know which is which. Pick one settle time (e.g. 30 minutes) and never vary it. Then read each pair blindly and record which glass has the higher sediment — ties recorded and excluded, denominator noted. Measurable outcome: the day's P index = (screened glass higher ÷ pairs compared) × 100. Over the whole run, a mean P index outside the 2-standard-error band around 50% (≈44–56% at 300 pairs, ≈40–60% at 100 pairs) = the copper screen systematically changes the settling rate, the core Piccardi claim, and one the textbooks say should not exist; a mean sitting inside that band = the P index is measuring nothing, a clean negative worth recording with a Skeptic's Star. Second, weaker arm: log Kp index and",
     "subjects": [
      "Science",
      "Measurement",
      "Water",
      "Self-Reliance"
     ],
     "passFail": "PASS (screen effect): mean P index over the whole run falls outside the 2-SE band around 50% (≈44–56% at 300 compared pairs; ≈40–60% at 100) — a thin copper screen systematically changes BiOCl settling | PASS (shielding, optional): copper screen and cardboard control produce different P indices | PASS (cosmic, secondary): daily P index correlates with Kp index or sunspot number in the reported dir",
     "sourceNote": "sources/alkemix/researchers/giorgio-piccardi.md (in-repo researcher fact sheet) + AFLinks Vault Rex Research Piccardi collection, doc ids 3606–3614 and 3686 (The Chemical Basis of Medical Climatology)",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-18-spiral-pipe-friction",
     "date": "2026-09-18",
     "title": "Spiral-Pipe Friction Test",
     "emoji": "🌀",
     "guild": "Aetherforce — Dim Lumber Woodworking",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural",
      "homestead"
     ],
     "status": "proposed",
     "desc": "In 1952, at the Stuttgart Technical College, Professor Franz Pöpel ran water through pipes of different shapes and materials to settle whether Viktor Schauberger was a crank. The straight glass tube resisted water the most. The straight copper tube resisted it less — same shape, different metal. Then came the spiral pipe, built on the curve of a kudu antelope's horn, and the result that has echoed through the vortex lineage ever since: at a high flow rate the resistance dropped to zero and went negative. The water, in Pöpel's own words, frees itself from the walls and flows through the tube. E",
     "steps": "Set a bucket or tote at a fixed measured height above an outlet — mark the water line, and refill to it every single run. Prepare three tubes of the same inner diameter and the same length: a straight copper tube, a straight glass tube, and a spiral copper tube (a pre-coiled copper coil is fine; record its coil diameter and pitch). Run each tube in turn, alternating A-B-C on every repetition so drift and temperature cancel, and time how long each takes to fill the bucket. Flow rate = volume ÷ time. Then go higher: repeat at a second, taller head, because the claim is specifically about HIGH flow — if the effect is real it should be absent at a trickle and appear at speed. Measurable outcome: the spiral tube delivers ≥20% more water per minute than the straight tube of the same bore and length at the same head, and the gap widens as the head rises = the 1952 shaping effect shows up in your own yard; all three tubes within ±10% = the anomaly does not reproduce, written down honestly, and you have saved every future family the guesswork. Then the craft arm: cut two wooden troughs or bored pipes, one straight and one with a spiral groove or angled baffles along its length, and run the ",
     "subjects": [
      "Science",
      "Engineering",
      "Measurement",
      "Craft"
     ],
     "passFail": "PASS (shape): spiral tube sustains ≥20% higher flow than straight copper tube of identical bore and length at equal head (mean of ≥3 alternating sessions), the gap widens at higher head, and the wooden spiral trough beats the straight trough in the same direction | PASS (material): straight copper sustains ≥10% more flow than straight glass at equal geometry | FAIL: all tubes within ±10% at every ",
     "sourceNote": "translations/2026-09-11-acqua-viva-viktor-schauberger-it.md (lines 3831–3945) — Olof Alexandersson, *Living Water: Viktor Schauberger and the Secrets of Natural Energy* (English ed. 1982; Italian ed. *Acqua Viva*), ch. 'Experiments at the Stuttgart Technical College'; corroborating restatement in tr",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-17-hammer-charged-blade",
     "date": "2026-09-17",
     "title": "Hammer-Charged Blade Test",
     "emoji": "🔨",
     "guild": "Aetherforce — Tool Care",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural",
      "homestead"
     ],
     "status": "proposed",
     "desc": "Viktor Schauberger claimed something strange about a scythe. Hammer the edge against a hardwood block — not an iron anvil — and the blade takes on a 'charge'; that charge is released at harvest and feeds the grass you cut; and if you leave the blade in the sun, the charge drains out and the edge goes 'flat.' He also said a hammered edge beats a ground one. Here is the part that makes it worth your bench: the sun claim has no other explanation. Same blade, same steel, same edge — an hour of sunlight is the only difference. If the charge is real, the sun blade cuts worse. If it isn't, the two bl",
     "steps": "Get three sickles or machetes of the same type (~$10–30 each). Peen two edges with a hammer on a hardwood block; file the third ('the normal way'). Leave one peened blade in full sun for an hour, the other in the dark. A family member who will not score codes all three and seals the key. Then the blinded bench: 10 uniform grass bundles per blade in randomized order, scorer counts strokes to sever each bundle; keep going until strokes double, and record strokes-to-failure. Finally mow three matched 1 m² plots, one per blade, and weigh regrowth at 2 and 4 weeks. Measurable outcome: blade B (sun) needs ≥15% more strokes than blade A (dark) in ≥2 of 3 sessions AND plot A out-grows plot B by ≥15% at 4 weeks = the charge claim shows up in your own yard; A and B within ±5% = the claim is retired honestly, and the A-vs-C result tells you what peening actually does to an edge. Run it as a neighborhood blade bench — two or more households contributing blades and pooling trials — so the numbers mean something.",
     "subjects": [
      "Science",
      "Measurement",
      "Craft"
     ],
     "passFail": "PASS: sun blade B needs ≥15% more strokes per bundle than dark blade A (blinded, mean) AND direction consistent in ≥2 of 3 sessions AND plot A regrows ≥15% more biomass than plot B at 4 weeks | FAIL: A and B within ±5% (or B cuts better) — honest negative, Skeptic's Star | INCONCLUSIVE: difference below threshold, blade geometry not equalized well enough to trust A vs B, or <3 sessions",
     "sourceNote": "translations/2026-09-11-acqua-viva-viktor-schauberger-it.md (lines 3262–3271) — Olof Alexandersson, *Living Water: Viktor Schauberger and the Secrets of Natural Energy* (English ed. 1982; Italian ed. *Acqua Viva*), ch. 'Biological Techniques in Agriculture'",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-17-qi-water-conductivity",
     "date": "2026-09-17",
     "title": "Qi-Water Conductivity Test",
     "emoji": "🙌",
     "guild": "Aetherforce — Natural Medicine",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "The energy-healing traditions say a person can emit a healing influence — Qi, Reiki, 'the gift.' The strongest version of that claim isn't 'it feels nice'; it's 'something changes matter.' In 1993 a Japanese team put it to a meter: 10 Qi senders imposed Qi on water and measured the water's electrical conductivity at 40±1°C. Their own results were mixed — three different conductivity curves from an identical method, and no imprint at all in purified water. Nobody in the archive has repeated it. You will. Code eight cups so the measurer stays blind, have someone attempt Qi on half of them while ",
     "steps": "Build a blinded water bench: one handheld EC/TDS meter (~$30–40), three water types (distilled, tap, mineral — each split from a single bottle across all cups), eight identical lidded glass cups, a thermometer, and a warm bath held at 40±1°C. First measure the meter's noise floor (10 repeated readings of one sample → standard deviation). Then a non-participating family member codes the cups A–H and seals the key. Measure baseline conductivity of every cup at 40±1°C; a 'sender' attempts Qi on half the cups while the other half is handled identically but with no attempt; re-measure blinded; repeat 3 sessions on different days, re-coding each time. Finally run the ions test — distilled vs tap vs mineral — because the 1993 study found Qi did NOT imprint into purified water. Measurable outcome: attempted-group mean conductivity change ≥2× the measured meter noise, direction consistent in ≥2 of 3 sessions, with no comparable shift in the handled-only controls = the healing claim showed up in an instrument in your kitchen; no difference = a clean, publishable null with the archive's own source cited.",
     "subjects": [
      "Science",
      "Measurement",
      "Health"
     ],
     "passFail": "PASS: blinded attempted-group EC change ≥2× measured meter noise AND direction consistent in ≥2 of 3 sessions AND handled-only controls show no comparable shift | FAIL: no difference between attempted and control groups, or both shift equally (handling/temperature, not Qi) — honest negative, Skeptic's Star | INCONCLUSIVE: effect below the 2× threshold, <3 sessions, or temperature/CO2 drift dominat",
     "sourceNote": "sources/2026-09-16-scout-a-de-fr-ja.md (find #9) — Sasaki, Sako & Kobayashi, J. Mind-Body Science 2(1), 1993, DOI 10.20788/jmbs.2.1_1",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-15-dodonov-ether-vortex",
     "date": "2026-09-15",
     "title": "Dodonov Ether Vortex Test",
     "emoji": "🌀",
     "guild": "Aetherforce — Woodland Care",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Demonstrate the formation of an ether vortex in water using a wooden spiral corrector (Dodonov corbio). Test whether vertical ether flows entering Earth from space can be detected through ink vortex formation. Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Fill a clear glass jar with still water. Add a few drops of dark ink through a tube to the bottom, letting it spread across the bottom. Place a wooden spiral-grooved corrector (cylinder with helical grooves) on top of the jar. Photograph the ink distribution every 15 minutes for 90 minutes. Measurable outcome: ink gathers toward center forming a vortex column extending upward.",
     "subjects": [
      "Science",
      "Woodland Care",
      "Self-Reliance"
     ],
     "passFail": "PASS: Ink forms central vortex column within 90 minutes, persists while corrector is present, dissipates within 15 minutes of removal. FAIL: Ink remains evenly spread or forms random patterns with no central convergence. INCONCLUSIVE: Weak central gathering that doesn't form clear column.",
     "sourceNote": "atsyukovsky-book5-ether-vortex",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-13-cold-vortex-germination",
     "date": "2026-09-13",
     "title": "Cold Vortex Water Germination Test",
     "emoji": "🌱",
     "guild": "Aetherforce — Water",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "Test Schauberger's +4°C water-vitality claim on real seeds: three trays, one watered with cold vortexed water, two controls. Germination is the verdict. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Schauberger claimed water near +4°C gains biological quality ('positive temperature movement'). Test it: sow 25 radish seeds in each of 3 trays. Arm A gets water vortex-stirred then chilled to 4°C; Arm B gets the same water chilled but unstirred; Arm C gets room-temperature water. Water daily with equal volumes for 10 days. Record germination count daily. Target: measurable difference between arms, with Arm A ≥ controls if the claim holds — or an honest refutation if it doesn't.",
     "subjects": [
      "Science",
      "Gardening",
      "Water"
     ],
     "passFail": "PASS: cold-vortex arm germination ≥ room control by ≥15 points AND ≥ cold-unstirred control. FAIL: cold-vortex arm underperforms room control, or matches the cold-unstirred arm (effect is temperature, not vortex). INCONCLUSIVE: <40% germination in all arms or <5-point spread.",
     "sourceNote": "translation:2026-09-11-compendium-of-vortex-physics-schauberger-de (p.88-89, positive temperature movement)",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-13-moonlight-germination",
     "date": "2026-09-13",
     "title": "Moonlight Germination Test",
     "emoji": "🌙",
     "guild": "Aetherforce — Food",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "Moon planting is the oldest claim in the archive — and in 2023 a peer-reviewed study found real cellular changes from full moonlight. Test it yourself: two trays of seeds, one sleeping under the full moon, one in a dark box. The kitchen scale decides. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Sow 25 mustard or radish seeds in each of 2 trays. On the 3 nights around the next full moon, place both trays in a spot that receives direct moonlight — cover one tray with an opaque box from dusk to dawn. Same soil, same water, same daylight. Count germination daily; at day 10-12 cut and weigh all seedlings per tray. Target: moonlight tray at least 15% heavier than the dark tray if the 2023 finding holds at home scale — or an honest refutation of the lunar-planting lineage where it's strongest.",
     "subjects": [
      "Science",
      "Gardening",
      "Food"
     ],
     "passFail": "PASS: moonlight arm fresh mass ≥ dark arm by ≥15% AND germination ≥ dark arm. FAIL: moonlight arm ≤ dark arm on fresh mass. INCONCLUSIVE: moon blocked by clouds ≥2 of 3 nights, artificial light reached the trays, or germination <40% in both arms — rerun next full moon.",
     "sourceNote": "sources:steiner-roots-2026-09-13 (Nugget 1 — Singiri et al. 2023, Plants 12(5):1121)",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-11-ez-water-exclusion-zone",
     "date": "2026-09-11",
     "title": "EZ Water Exclusion Zone Test",
     "emoji": "💧",
     "guild": "Aetherforce — Water",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "Visualize Pollack's exclusion zone water at hydrophilic interfaces. Measure particle-free zone width and IR-driven growth. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Place a hydrophilic surface (Nafion sheet or treated glass) in water with microsphere suspension. Wait 15 minutes for particles to settle. Using a microscope (100-400×), observe the particle-free exclusion zone forming near the surface. Measure EZ width at 5 points and calculate average. Illuminate with IR lamp or sunlight for 20 minutes and remeasure. Target: EZ ≥100 μm baseline, ≥20% growth under IR.",
     "subjects": [
      "Science",
      "Water",
      "Biology"
     ],
     "passFail": "EZ width ≥100 μm visible AND ≥20% growth under IR illumination",
     "sourceNote": "scout:2026-09-04-scout-a-de-fr-es-ru-it-ja-zh#entry-9",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-10-vortex-jet-turbine",
     "date": "2026-09-10",
     "title": "Vortex Jet Turbine Energy Test",
     "emoji": "🌀",
     "guild": "Aetherforce — Power",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test Schauberger's 1930 jet-turbine claim: spiral vortex induction makes flowing water deliver more power than a straight pipe at the same head. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Mount a small DC water turbine generator ($20-40) at a fixed 1 m head. Run three intake configs, 5 runs each, alternating order: (A) straight 3-4cm pipe control, (B) same pipe with a jet restriction reducing to 1-1.5cm, (C) jet + spiral ribs or angled vanes inducing a vortex. Each run: record voltage and current into a fixed 10-50 ohm resistor load for 60s, time a bucket fill for flow rate (L/s), measure inlet vs outlet water temperature. Compute P = V·I per run. Measurable outcome: C beats A by >15% AND beats B by >10% beyond run-to-run spread, with flow not dropping enough to explain the gain = supports the vortex-efficiency claim; C within noise of B = spiral ribs add nothing at home scale; flow varying >10% between runs = inconclusive.",
     "subjects": [
      "Science",
      "Engineering",
      "Energy"
     ],
     "passFail": "C > A by >15% AND C > B (jet-only control) by >10% beyond noise = PASS; C ≈ B = FAIL (ribs add nothing); flow variance >10% or output <0.5 W = INCONCLUSIVE",
     "sourceNote": "translations/2026-09-09-schauberger-dynamic-hydroelectric-energy-es.md",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-09-hyperbolic-funnel-vortex",
     "date": "2026-09-09",
     "title": "Hyperbolic Funnel Vortex Aerator",
     "emoji": "🌀",
     "guild": "Aetherforce — Water",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "Build Walter Schauberger's hyperbolic funnel water vortex. Test aeration efficiency against control. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Construct a hyperbolic funnel (acrylic or glass, 10-15cm upper diameter, 1-2cm lower outlet, 20-30cm height) following Walter Schauberger's profile. Establish a stable free-surface water vortex. Measure dissolved oxygen before and after 30 minutes of operation. Calculate SOTR (Standard Oxygen Transfer Rate). Compare to bubble diffuser control if available. Target: SOTR exceeds 2× control at same power input.",
     "subjects": [
      "Science",
      "Engineering",
      "Water"
     ],
     "passFail": "SOTR > 2× control OR stable vortex with visible air entrainment in Regime B",
     "sourceNote": "scout:2026-08-29-scout-b-es-fr-zh#entry-4",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-06-wasserwirbler",
     "date": "2026-09-06",
     "title": "Build the Wasserwirbler (Vortexer)",
     "emoji": "🌀",
     "guild": "Plumbing and Hot Water",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Build a water vortexer and test the Schauberger water claims (temp + taste).",
     "steps": "Build a hyperbolic funnel with a threaded outlet; pour water through in a centripetal spin. Run the blind temperature test (A) and taste test (B) from dossier 001. Record all numbers + photos.",
     "subjects": [
      "Science",
      "Engineering"
     ],
     "passFail": "Temp: consistent ≥0.3°C difference vortexed vs control (4/5 trials). Taste: vortexed picked as 'softer/rounder' ≥8/10 blind.",
     "sourceNote": "scout find 2026-09-05 #9 (Orpanit, 'Viktor Schauberger und der Wasserwirbler') + Schauberger 1951 Luxembourg patent 31,480 (translation)",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    }
   ]
  },
  {
   "id": "eeman-circuit",
   "name": "Eeman Circuit",
   "emoji": "⚡",
   "subtitle": "electricity, biofields & subtle energy tests",
   "cards": [
    {
     "id": "2026-09-23-sealed-box-electrostatic-thrust",
     "date": "2026-09-23",
     "title": "Sealed-Box Electrostatic Thrust Test",
     "emoji": "⚡",
     "guild": "Aetherforce — Propulsion",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Two engineers — one of them the lead of NASA's electrostatics laboratory — say an asymmetric electrostatic device makes thrust that is not ion wind, and they demonstrate the contrast with a balsa lifter in a sealed plastic box on a scale. That box is the whole experiment: a closed box closes the momentum budget, so a thrust made by pushing air out of the system must vanish inside it. Build both devices — the lifter that is supposed to read flat, and the blade-geometry article that is supposed to read non-flat — and put them in the same box on the same scale. The lifter is not a warm-up; it is ",
     "steps": "Build two articles: (A) a balsa lifter — aluminium-foil plate 3–4 cm wide, corona wire 0.2–0.4 mm, on a light frame; (B) a single-stage electrostatic-pressure article in the blade geometry — one electrode carrying a proximal conductive face close to a flat opposing plate and a distal face further away, joined by a conductive web, the two held apart by a NON-conductive brace. Power both from a current-limited, enclosed 10–50 kV supply. Put a 0.01 g scale under the rig. First run the OPEN arm: device on the stand, powered off vs on, 10 alternating cycles, for both articles — this proves the rig can see a thrust at all. Then run the SEALED arm: device and stand inside a clear plastic box with a lid, the BOX on the scale, power fed through a slack flexible lead with a service loop so it cannot push or pull, 10 alternating cycles, for both articles. Run a mass-matched dummy on the same lead as the lead-artifact control. Repeat with each device flipped 180° and with polarity reversed — the claim predicts the reading reverses on flip; ion wind does not. Repeat the whole thing in three sessions on different days. Measurable outcome: delta-mass in grams (powered off minus powered on) for ea",
     "subjects": [
      "Science",
      "Engineering",
      "Energy"
     ],
     "passFail": "PASS: blade article delta-mass in the sealed box >= 0.5 g (>=5 mN), at least 10x the mass-matched dummy's reading, with the balsa lifter control flat in the same box (|delta| <= 0.1 g) and the reading reversing on device flip - repeated in three separate sessions. FAIL: blade article flat in the sealed box (within 2x the dummy's noise) while the lifter shows a clear thrust in the open arm - the fo",
     "sourceNote": "sources/2026-09-14-deep-dive-morning-a#find-2 (Exodus/Buhler New Force) + translations/2026-09-22-shipov-institute-vacuum-physics-experiments-ru (Brown asymmetric capacitor construction) + sources/2026-09-17-patent-watch#1 (US 12,715,620, Biefeld-Brown thrust claim)",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-21-chiappini-planetary-antenna",
     "date": "2026-09-21",
     "title": "The Proton Antenna",
     "emoji": "📡",
     "guild": "Aetherforce — Power",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "An Argentine radio amateur asked a question his textbooks skipped: why does the teaching of radio propagation leave out the electric displacement field, the very term Maxwell needed to make his equations complete? Working it through, he found a set of geometric constants and bent a single 63 cm piece of wire into the wireframe of a tiny planet — four meridians and an equator — and mounted it on a coax connector. Total radiating length: 49 cm. He reports that this little 'Proton' antenna, 5 m up and running 1 W from a cheap handheld, reaches 25 km across a city — and he is unusually honest that",
     "steps": "Cut 63 cm of stiff messenger wire and mark it from one end: 10 cm for the connector, then 4.1 cm, 16.3 cm, 4.1 cm, then three × 8.2 cm. Bend the segments around a ~5.2 cm form into four meridians and an equator — a wireframe sphere — keeping the meridian planes perpendicular and each meridian advancing in the equator's direction. Solder on a PL259 with the south pole 8.3 mm from the connector, leaving ~1.5 cm of excess wire to trim in tenths of a millimeter while watching performance. Then measure: sweep SWR at 144.0, 145.0, 146.0, 147.0 and 148.0 MHz with a NanoVNA, in the final mounting position, and do the same for a reference antenna (the handheld's stock rubber-duck or a quarter-wave ground-plane). Finally, with a second station, transmit at 1 W on the same day from the same two locations and record the maximum distance each antenna stays intelligible, averaged over at least 3 runs. Measurable outcome: SWR below 2.0 across the band AND range equal to or better than the reference antenna, reproducing on a second build = the D-field design holds up on your bench; SWR above 2.0 in every position, or range clearly worse than the reference = the claim is retired honestly.",
     "subjects": [
      "Science",
      "Engineering",
      "Self-Reliance"
     ],
     "passFail": "PASS: SWR < 2.0 across 144–148 MHz in the final mounting position AND range at 1 W equal to or greater than the reference antenna (same day, same locations, ≥ 3 runs) AND the result reproduces on a second build | FAIL: SWR ≥ 2.0 across the band in every mounting position (the author's own discard criterion), or range clearly worse than the reference, or the antenna cannot be tuned into the band — ",
     "sourceNote": "translations/2026-09-18-planetary-antenna-d-field-chiappini-es.md — 'Antena Planetaria (Planetary Antenna),' Carlos Alejandro Chiappini's full construction guide and D-field theory appendix (viXra:2110.0093, 2021-10-17)",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-17-earth-energy-grid-instrument-scan",
     "date": "2026-09-17",
     "title": "Earth-Energy Grid Instrument Scan",
     "emoji": "🧭",
     "guild": "Aetherforce — Earthworks",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "The geobiology tradition says the Earth is wrapped in a grid of 'earth radiation' lines — the Hartmann grid, running N-S and E-W about 2 m apart. Every test of it so far used dowsing rods. No one has ever found it with an instrument. You will. Fix a phone in a cardboard jig (fixed height, fixed orientation), open a free magnetometer app, and walk a 1 m grid across two rooms and your yard, logging the magnetic field (µT) at every point. Repeat three times, average the runs, and plot field vs position. Measurable outcome: a repeating pattern at ~2 m spacing whose amplitude rises clearly above yo",
     "steps": "Build a fixed-orientation cardboard jig for a phone, open a free magnetometer app, and record the noise floor (30 still readings). Lay a 1 m measurement grid across two rooms and the yard, log the magnetic field (µT) at each point, and repeat each grid 3 times. Average the passes and plot field vs position. Measurable outcome: a repeating ~2 m-period structure present in ≥2 of 3 averaged runs with amplitude ≥3× the noise floor = the grid is a real magnetic structure in your home; no structure above noise = the tradition's instrument-detection gap stays open, honestly.",
     "subjects": [
      "Science",
      "Measurement",
      "Observation"
     ],
     "passFail": "PASS: repeating ~2 m-period structure in ≥2 of 3 averaged runs AND amplitude ≥3× measured noise floor | FAIL: no periodic structure above noise in any room (honest negative, Skeptic's Star) | INCONCLUSIVE: structure below threshold or <3 passes",
     "sourceNote": "translations/2026-08-29-hotie-viviane-broceliande-fr-en.md",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-14-bladeless-tesla-turbine",
     "date": "2026-09-14",
     "title": "Bladeless Tesla Turbine Static Electricity Test",
     "emoji": "⚡",
     "guild": "Aetherforce — Power",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test the 2026 bladeless Tesla turbine claim: compressed air + electrostatic injection generates usable electrical output beyond either alone. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Build a bladeless Tesla turbine (5-10 smooth disks, 1-2 mm spacing) on low-friction bearings. Connect compressed air (2-4 bar) via tangential nozzle at disk edges. Add electrostatic generator (10-50 kV) with electrode injecting charges into airflow upstream of turbine. Wire electrical pickup (brushes or induction coil) to multimeter and oscilloscope. Run three configs, 5 runs each, alternating order: (A) air only, (B) electrostatic only, (C) combined. Each run: log voltage, current, RPM (tachometer), airflow (anemometer), ambient static before/after. Measurable outcome: C produces V > 10V and I > 0.1A while A and B produce negligible output, with RPM 6,800-10,100 and airflow 240-360 m/s = supports electrostatic conversion claim; C within noise of A or B = combined effect does not replicate at home scale; RPM/airflow significantly below range = inconclusive (mechanical issues).",
     "subjects": [
      "Science",
      "Engineering",
      "Energy"
     ],
     "passFail": "C produces V > 10V and I > 0.1A while A and B produce negligible output, with RPM 6,800-10,100 and airflow 240-360 m/s = PASS; C within noise of A or B = FAIL (no combined effect); RPM/airflow below range = INCONCLUSIVE",
     "sourceNote": "sources/2026-08-29-scout-b-es-fr-zh.md",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-14-orgone-accumulator-tot",
     "date": "2026-09-14",
     "title": "Orgone Accumulator Temperature Test",
     "emoji": "🌡️",
     "guild": "Aetherforce — Oddball",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test whether a Reich orgone accumulator (layered steel wool + organic material) produces a measurable temperature difference beyond convection. The discriminating experiment Einstein himself requested in 1941. Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Build a 3-ply orgone accumulator (steel wool + cotton/wool layers, ~30cm cube) and a thermodynamically-matched solid-wall control box. Install differential thermocouples in both. Log interior vs ambient temperature every 5 minutes for 30 days. Third party blinds the sensor labels. Measurable outcome: ORAC exceeds control by ≥0.1°C on average, with weather-state correlation.",
     "subjects": [
      "Science",
      "Health",
      "Self-Reliance"
     ],
     "passFail": "PASS: ORAC ≥0.1°C warmer than control, correlates with weather (higher in clear/dry), second-harmonic present. FAIL: no significant difference, or control warmer. INCONCLUSIVE: small difference that doesn't reach significance.",
     "sourceNote": "dossier-017-orgone-accumulator-tot",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-12-eeman-sleep-quality",
     "date": "2026-09-12",
     "title": "Sleep Quality Biofield Test",
     "emoji": "🌙",
     "guild": "Aetherforce — Natural Medicine",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test whether the Eeman self-connecting copper circuit (no power) improves sleep quality when used before bed. Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Build an Eeman circuit (insulated copper wire, head band, hand/foot contacts, ~$10). Use it for 15 minutes before bed on 7 nights (randomly selected). Compare sleep quality (duration, wake-ups, morning alertness) vs 7 control nights (no circuit). Log each morning. Measurable outcome: sleep quality score difference ≥15% supports the claim.",
     "subjects": [
      "Science",
      "Health",
      "Self-Reliance"
     ],
     "passFail": "PASS: circuit nights ≥15% higher sleep quality score vs control, replicates across ≥2 testers. FAIL: no meaningful difference (within 5%). INCONCLUSIVE: small difference that doesn't replicate.",
     "sourceNote": "dossier-012-eeman-sleep-quality",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-12-form-waves-space-harmony",
     "date": "2026-09-12",
     "title": "Form Waves Space Harmony Test",
     "emoji": "🔷",
     "guild": "Aetherforce — Natural Building",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Apply sacred geometry principles to understand how forms affect spaces. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Test whether geometric forms (Flower of Life, golden spiral, pyramid) measurably change your energy field distance as detected by dowsing rods. Use a blank paper control. Report baseline, form, and control distances.",
     "subjects": [
      "Science",
      "Geometry",
      "Observation"
     ],
     "passFail": "PASS: Form distance ≥20% larger than baseline AND control. FAIL: No consistent difference (within 10%).",
     "sourceNote": "translations/2026-08-29-ondes-de-forme-vibratis-fr-en.md",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-10-eeman-animal-calm",
     "date": "2026-09-10",
     "title": "Eeman Circuit for Animal Calm",
     "emoji": "🐾",
     "guild": "Animal Care",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test whether the Eeman circuit calms animals (pets/livestock) — blind behavior observation.",
     "steps": "Build the Eeman circuit (same as human test — ~$10 copper wire). Test on one animal (dog, cat, horse, chicken) using the blind protocol from dossier 006: circuit vs sham, 5 sessions, observe restlessness + breathing + vocalizations. Record all observations + photos.",
     "subjects": [
      "Science",
      "Animal Care"
     ],
     "passFail": "Circuit shows calmer behavior vs sham (same direction ≥4/5 sessions, delta ≥2 restlessness points or ≥3 breaths/30s).",
     "sourceNote": "dossier 002 (Eeman human circuit) + biofield tradition extension",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-10-electrostatic-energy-test",
     "date": "2026-09-10",
     "title": "Electrostatic Energy Balance Test",
     "emoji": "⚡",
     "guild": "Aetherforce — Community",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test whether electrostatic machines can extract vacuum energy, as claimed by the Methernita community's 750 kW Testatika system running since 1980.",
     "steps": "Build or buy a Wimshurst machine ($50-100). Crank for 60 seconds to charge a capacitor bank (20-40µF, 400V). Close switch to LED array. Time how long LED stays lit (>50% brightness). Calculate energy: E = ½CV². Compare output to cranking input work. Measurable outcome: LED illumination time > 66 seconds (10% above cranking duration) AND calculated output > input by >10% = supports claim; LED time ≤ 60s or output ≤ input = refutes claim.",
     "subjects": [
      "Science",
      "Engineering",
      "Energy"
     ],
     "passFail": "LED illumination >66s AND calculated output > input by >10% = PASS; LED ≤60s or output ≤ input = FAIL; machine fails to charge = INCONCLUSIVE",
     "sourceNote": "translations/2026-09-04-shipov-torsion-fields-ru-en.md",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-09-blind-geopathic-mapping",
     "date": "2026-09-09",
     "title": "Blind Geopathic Zone Mapping",
     "emoji": "📡",
     "guild": "Aetherforce — Nest",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "Can two people walking the same room with dowsing rods find the SAME earth-energy lines without seeing each other's maps? The geobiology tradition (Hartmann grid, Curry lines) says yes; the 1991 Kassel test says no. Your family settles it for your own home — with numbers. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Bend two sets of L-rods from coat hangers (~$5). Two family members each map the SAME room independently — wherever the rods cross, record the position by tape measure from two walls. Then both map a second room. A referee (great kid job) overlays the maps: same-room agreement vs cross-room agreement (the chance baseline). Run 3 sessions. Measurable outcome: same-room agreement ≥70% AND ≥25 points above the cross-room chance baseline = the lines are real for your home; agreement at chance = the rods found nothing shared, honestly retire the advice.",
     "subjects": [
      "Science",
      "Observation",
      "Family"
     ],
     "passFail": "Same-room agreement ≥70% across ≥3 sessions AND ≥25 points above cross-room chance baseline (PASS) | within 10 points of chance (FAIL — honest negative, Skeptic's Star)",
     "sourceNote": "scout:2026-08-30-scout-b-de-ru#entry-1",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-08-tesla-radiant-receiver",
     "date": "2026-09-08",
     "title": "⚡ Aetherforce · Homesteading complement — Build the Radiant Energy Receiver",
     "emoji": "⚡",
     "guild": "Aetherforce — Power",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Build Tesla's 1901 radiant energy receiver — an elevated insulated plate charging a capacitor to ground — and measure what the sky actually gives you. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault",
     "steps": "Mount an insulated metal plate 3-5 m up on a NON-metal pole, wire it through a film capacitor to a ground rod, and measure voltage at 0/5/10/15 min across 5+ sessions (morning/noon/night, clear/overcast). Then wrap the plate in grounded foil as the control and repeat. PASS: receiver reads ≥10× the shielded control in ≥4/5 sessions. Storms: always disconnect and ground the antenna first.",
     "subjects": [
      "Science",
      "Engineering"
     ],
     "passFail": "Receiver accumulates charge ≥10× above shielded control, same direction in ≥4/5 sessions → collection confirmed (mechanism unresolved); compute stored energy ½CV² and report honest micro-watt scale. No accumulation above control → does not replicate at home scale; log as refuted.",
     "sourceNote": "translation 2026-09-03-tesla-patents-radiant-energy-fr (Tesla radiant energy patent schematics analysis, Lindemann compilation, FR→EN) + scout find 2026-08-26-a #2",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    }
   ]
  },
  {
   "id": "kitchen-lab",
   "name": "Kitchen Lab",
   "emoji": "🥚",
   "subtitle": "food, fermentation & living processes",
   "cards": [
    {
     "id": "2026-09-24-succession-order-planting",
     "date": "2026-09-24",
     "title": "Succession-Order Planting Test",
     "emoji": "🌱",
     "guild": "Aetherforce — Gardening",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "A forest doesn't plant itself all at once — pioneers come first, then the shrubs, then the trees, each making the ground ready for the next. Ernst Götsch's method claims that this ORDER is the critical factor: that a plant establishes because of WHEN it enters the succession, more than because of light or soil. This is a test of that claim on YOUR ground: three identical plots with the same three plants — one planted in succession order, one all at once, one monoculture — and one season of measuring which plants actually make it. You get your own numbers for whether timing beats density, and a",
     "steps": "Pick three species in three roles — a fast pioneer (a quick legume or leafy annual), a main crop you actually want, and a later-succession woody/long-lived plant. Lay out three equal adjacent plots on the same ground: A (succession order), B (all at once), C (main crop alone). Plant Plot B with all three together and Plot C with the crop alone. In Plot A, plant the pioneer FIRST; when it is established and in vigorous growth, plant the crop beneath it; when that is established, plant the woody species. Manage all three identically (same water, selective weeding only, no pruning yet). At ~8 and ~16 weeks, record per species per plot: survival %, mean height of survivors, and final above-ground biomass; plus main-crop yield and soil-surface cover %. Then split Plot A in half — chop-and-drop the maturing plants in one half, leave the other — and measure new-shoot growth over 4 weeks. Measurable outcome: later-succession species survival and biomass in Plot A vs Plot B; total community biomass A vs B vs C; crop yield A vs B vs C; new growth in the pruned vs unpruned half. Target: Plot A woody survival >= 2x Plot B AND Plot A total biomass >= 1.3x Plot B AND Plot A crop yield >= Plot B'",
     "subjects": [
      "Science",
      "Observation",
      "Earth Care"
     ],
     "passFail": "PASS (order matters): the later-succession species' survival in Plot A is >= 2x that in Plot B AND Plot A total community biomass is >= 1.3x Plot B's AND Plot A main-crop yield is >= Plot B's - and the direction repeats in a second planting round or second season. PASS (pruning rejuvenates): over 4 weeks, Plot A-pruned new-shoot growth is >= 1.5x A-unpruned with no rise in mortality. FAIL: Plot A ",
     "sourceNote": "sources/2026-09-22-scout-a-langs-2#find-9 (Ernst Götsch, 'Natural Succession of Species in Agroforestry and in Soil Recovery', Fazenda Três Colinas, Bahia, 1992)",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "kitchen-lab"
    },
    {
     "id": "2026-09-22-element-day-sowing",
     "date": "2026-09-22",
     "title": "Element-Day Sowing Test",
     "emoji": "🌱",
     "guild": "Aetherforce — Food",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "The biodynamic calendar says a leaf crop sown on a 'leaf day' beats the same seed sown on a 'root day'. One 1976 trial found a swing that large; an 8-year trial found nothing. Settle it on your own shelf: sow one pot a day for a full moon-cycle, weigh every pot blind, and only then look at the calendar. The scale decides. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Sow one pot of radish, mustard or lettuce every day for 27 days — same seed count, same soil, same water, pots numbered 1-27 with no dates on them, rotated one place along the shelf daily. Harvest each pot 28 days after its own sowing and weigh its fresh mass in grams. Weigh everything BEFORE anyone looks at the calendar, then unblind and group the pots by element day (leaf / root / fruit / flower). Target: leaf-day pots at least 20% heavier than root-day pots if the calendar claim holds — or an honest refutation of the sidereal sowing calendar at home scale.",
     "subjects": [
      "Science",
      "Gardening",
      "Food"
     ],
     "passFail": "PASS: leaf-day pots average >=20% more fresh mass than root-day pots AND the group ordering runs in the predicted direction (leaf > flower/fruit > root). FAIL: all element-day groups within +/-10% of each other. INCONCLUSIVE: germination <50% in any group, a pot lost or dried out, the calendar key was opened before weighing, or within-group spread exceeds 40% of the mean.",
     "sourceNote": "sources:steiner-roots-2026-09-13 (Nugget 6 — Bishop lettuce trial, reported in Kollerstrom & Staudenmaier 2001)",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "kitchen-lab"
    },
    {
     "id": "2026-09-19-electroculture-growth-stimulation",
     "date": "2026-09-19",
     "title": "Electro-Culture Growth Stimulation Test",
     "emoji": "🌱",
     "guild": "Aetherforce — Gardening",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural",
      "homestead"
     ],
     "status": "proposed",
     "desc": "In 1746 a doctor in Edinburgh pointed the output of an electrostatic generator at some myrtle plants and they grew and flowered better. People have been trying to electrify plants ever since — magnets, wires, coils, high voltage, sound, coloured light — and the results have been spectacular, contradictory, and never properly nailed down. This quest tests the two cheapest versions. First: hold seeds near a magnet's north pole before you plant them. A mid-century researcher named U.J. Pittman claimed that alone makes many seeds germinate about twice as fast, and wheat grow about five times as mu",
     "steps": "Arm A (48 hours to first result): split one packet of wheat, radish or mung bean seeds three ways — N-pole, S-pole, and sham — 30-50 seeds each. An adult codes the trays so the person measuring does not know which is which. Treat each batch with its magnet (or a non-magnetic steel slug of the same size for the sham) at the same measured gap for the same fixed duration — 24 hours is a good first choice — and record the gap and the duration. Sow each batch into an identical tray with the same medium, water and depth, and rotate tray positions daily. At 48 hours, count germinated seeds (define germination once, up front — radicle at least 2 mm) and measure every shoot with a ruler, blind. Repeat at day 7 and day 14. Measurable outcome: the N-pole batch shows at least 20% higher germination or 30% greater 48-hour shoot length than the sham, as a mean across two independent runs, and the S-pole batch does not simply match the N-pole batch. Arm B (4-6 weeks): bend a single loop of stiff copper wire 15-30 cm across with the ends overlapping and separated by a small gap, stand it on a plastic support around one of two matched potted seedlings, swap their positions every 2-3 days, and measu",
     "subjects": [
      "Science",
      "Biology",
      "Gardening",
      "Self-Reliance"
     ],
     "passFail": "PASS (magnetic arm): N-pole batch shows >=20% higher germination OR >=30% greater 48-hour shoot length than the sham, as a mean across two independent runs, AND the S-pole batch does not equal the N-pole batch (i.e. the effect is not just 'any magnet') | PASS (coil arm): coiled plant shows >=20% greater growth than its matched control over 4-6 weeks, repeated with a second plant pair | FAIL: all t",
     "sourceNote": "doc:1810 (Electro-Culture: Stimulation of plant growth with electricity, magnetism, sound, &c — Robert A. Nelson, rexresearch.com) + doc:1359 (Corson & Zaderej — Electrogenics, US Patent 4,302,670) + Vault ElectroCulture collection: doc:2900, doc:5524, doc:5539, doc:3824, doc:3143, doc:1222, doc:230",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "kitchen-lab"
    },
    {
     "id": "2026-09-16-korschelt-aether-ray-ripening",
     "date": "2026-09-16",
     "title": "Korschelt Aether-Ray Ripening Test",
     "emoji": "🍷",
     "guild": "Aetherforce — Commerce",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test Oskar Korschelt's 1892 claim that a galvanic-element 'aether ray' apparatus ripens sealed wine and spirits — improving their taste — and promotes plant growth. Run a blind triangle test to see whether the taste change survives when the taster doesn't know which bottle was treated. Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Build a simplified Korschelt ray apparatus: a sheet-metal tube with two discs ~4 cm apart connected to a low-voltage DC source, plus a wire spiral along the tube. Split 6 matched bottles of a young wine or spirit into treated (3, inside the tube, energized 2-7 days) and control (3, same room, unpowered). Then run a blind triangle test: 9 trials, each with 3 cups (two from one bottle, one from the other), taster identifies the odd cup and states a preference. Measurable outcome: taster correctly identifies the odd cup in at least 6 of 9 trials (p<0.05). Optional plant arm: run the Fig. 10 star-disc apparatus under one of two matched potted plants for 14 days and compare new shoot growth.",
     "subjects": [
      "Science",
      "Commerce",
      "Food",
      "Self-Reliance"
     ],
     "passFail": "PASS: Taster identifies the odd cup in >=6 of 9 blind triangle trials (p<0.05) AND prefers the treated sample in a majority of trials; plant arm shows >20% greater new shoot growth than control, repeated in a second run. FAIL: <=3 of 9 correct (chance) — taste effect not detectable blind. INCONCLUSIVE: 4-5 of 9 correct, or effect in one beverage type only, or plant difference within measurement no",
     "sourceNote": "korschelt-1892-aether-ray-ripening",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "kitchen-lab"
    },
    {
     "id": "2026-09-11-egg-fermentation-vessel",
     "date": "2026-09-11",
     "title": "Egg-Shaped Fermentation Test",
     "emoji": "🥚",
     "guild": "Aetherforce — Food",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test whether egg-shaped fermentation vessels produce superior outcomes compared to cylindrical vessels. Schauberger claimed the egg form is ideal for water storage and that fermentation at +4° to +9°C with light exclusion produces higher-grade processes. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Prepare identical sauerkraut batches in an egg-shaped container and a cylindrical container. Track pH daily for 14 days. Record: time to target pH (≤3.7), visual fermentation activity, mold presence, and final taste. Conduct blind taste test with 3+ family members. Report: vessel type used, pH log, photos, taste scores, and whether egg vessel showed measurable advantage.",
     "subjects": [
      "Fermentation",
      "Food Preservation",
      "Experimental Science"
     ],
     "passFail": "PASS if egg vessel reaches target pH faster OR shows fewer off-flavors OR wins blind taste test. FAIL if no measurable difference or cylinder performs better. INCONCLUSIVE if both fail to ferment properly.",
     "sourceNote": "translations/2026-09-09-compendium-of-vortex-physics-de.md",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "kitchen-lab"
    }
   ]
  },
  {
   "id": "form-shelter",
   "name": "Form & Shelter",
   "emoji": "🏠",
   "subtitle": "natural building & shape effects",
   "cards": [
    {
     "id": "2026-09-22-pyramid-storage-desiccation",
     "date": "2026-09-22",
     "title": "Pyramid Storage Desiccation Test",
     "emoji": "🔺",
     "guild": "Aetherforce — Shelter",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "The pyramid tradition says organic matter left inside a cardinal-aligned pyramid desiccates instead of rotting — the mummification claim behind a century of pyramid-power folklore. Nobody has ever published the protocol, so build it yourself: three matched samples, one in a pyramid, one under a plain box of the same size, one in the open. Weigh and photograph every day for three weeks. If the pyramid sample dries while the others rot, you have something; if the box does the same, you have learned what the box does. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Sour",
     "steps": "Build a cardboard pyramid to the Czech numbers (triangles 159 mm high, base 250 mm, edge 238 mm, ventilation holes at base and apex) and a plain box of the same footprint with a flat top. Weigh three matched samples of the same fruit or meat to within 5% of each other, code them A/B/C with a sealed key, and place one in each station on identical supports at 1/3 the pyramid's height, all in the same room, same distance from any wall. Weigh and photograph all three daily for 21 days and record mold present-or-absent each day. Unblind only after the last number is written. Target: the pyramid sample ≥20% more mass loss than BOTH controls with no mold where a control molds — or an honest refutation of the desiccation claim at home scale.",
     "subjects": [
      "Science",
      "Food",
      "Shelter"
     ],
     "passFail": "PASS: by day 21 the pyramid sample has lost >=20% more mass than BOTH controls AND shows no mold where at least one control has molded, and the direction repeats in a second run with a fresh set. FAIL: all three samples within +/-10% on mass loss AND mold status identical. INCONCLUSIVE: starting masses differ by more than 5%, room conditions swing between stations, a sample is disturbed or eaten, ",
     "sourceNote": "translations:2026-09-18-ondes-de-forme-centre-ganesha-fr (the pyramid-desiccation claim) + sources:2026-09-18-scout-b-langs-1 (find 3 — Bovis lineage, construction numbers)",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "form-shelter"
    },
    {
     "id": "2026-09-19-drbal-pyramid-blade-retention",
     "date": "2026-09-19",
     "title": "Pyramid Blade-Retention Test",
     "emoji": "🔺",
     "guild": "Aetherforce — Metalworking",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural",
      "homestead"
     ],
     "status": "proposed",
     "desc": "In 1949 a Prague engineer filed a patent for keeping razor blades sharp with no power, no heat, no abrasives, no chemicals — just a cardboard pyramid. The blade sits inside it, edge east-west, on a cork at a third of the height, and the patent says the metal's crystal lattice relaxes and the edge comes back. The patent office granted it in 1959, and nobody has ever tested it at home. Here is the test: two identical blades from the same pack. One lives in the pyramid, one sits on an identical cork right beside it — same room, same orientation, no cone. That is the only difference, and that is t",
     "steps": "Build a square-based cardboard pyramid to the patent's own numbers — height × π/2 for the base side (a 10 cm pyramid has a 15.7 cm base), side edges to the four diagonal compass points, a cork support at 1/5–1/3 of the height, a blade lying edge east-west. Set an identical cork station beside it with no cone: same room, same orientation, same dielectric base. An adult codes two identical blades from the same pack, seals the key, and puts one on each station for 14 days. Then run the blinded cut test — 5 strips of the same newspaper per blade, alternating, counting strokes to sever. Measurable outcome: the pyramid blade severs the strip in ≥30% fewer strokes than the open blade, repeated in a second 14-day run = the patent's storage claim shows up in your kitchen; within ±10% = the claim is retired honestly, and your family has the first home burial of Czechoslovak Patent 91304. Then run the long arm: shave with both blades on alternating days, return each to its own station, and count shaves to failure against a definition you wrote down before you started.",
     "subjects": [
      "Science",
      "Measurement",
      "Craft"
     ],
     "passFail": "PASS (storage arm): pyramid blade severs the standard strip in ≥30% fewer strokes than the open blade (median of 5 strips) AND the direction repeats in a second 14-day run | PASS (shave arm): ≥2× the shaves-to-failure of the control, strokes-to-sever series never crossing over | FAIL: within ±10% on strokes-to-sever and ±20% on shaves-to-failure — honest negative, Skeptic's Star | INCONCLUSIVE: ru",
     "sourceNote": "translations/2026-09-18-drbal-patent-91304-cs.md — Czechoslovak Patent Specification No. 91304, Karel Drbal (Prague), 'Method of maintaining razor blades and razors sharp', filed 4 Nov 1949, issued 15 Aug 1959; archived at archives/2026-09-18-drbal-patent-91304-cs.pdf",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "form-shelter"
    },
    {
     "id": "2026-09-13-wood-acoustic-resonance",
     "date": "2026-09-13",
     "title": "Wood Acoustic Resonance Test",
     "emoji": "🪵",
     "guild": "Aetherforce — Round Wood",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test whether wood grain density affects acoustic resonance. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Collect 3-5 wood samples from different trees or species. Count annual rings per inch. Tap each sample with consistent force and record the sound. Use a free sound analyzer app to measure sustain time (how long the note rings). Compare: Does tighter grain correlate with longer sustain?",
     "subjects": [
      "Science",
      "Woodworking",
      "Observation"
     ],
     "passFail": "PASS: Sample with tightest grain shows ≥20% longer sustain than sample with widest grain. FAIL: No consistent correlation between grain density and sustain time.",
     "sourceNote": "translations/2026-09-09-schauberger-water-blood-of-earth-de.md",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "form-shelter"
    }
   ]
  },
  {
   "id": "vitality",
   "name": "Vitality",
   "emoji": "🌿",
   "subtitle": "health, medicine & life forces",
   "cards": [
    {
     "id": "2026-09-22-neutral-pendulum-discrimination",
     "date": "2026-09-22",
     "title": "Neutral Pendulum Discrimination Test",
     "emoji": "🪢",
     "guild": "Aetherforce — Natural Medicine",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "A neutral pendulum on a string is said to be an extension of your own energy field — tune the string length to a quality and you feel a pull when that quality is present, nothing when it isn't. The instructor says it himself: an external skeptic will never believe it whether your hand is rock still or not. So test it blind. Learn the pull on known batteries, then let someone else code 40 containers you can't see and score your hits against chance. If the pull discriminates, you have a measurement skill; if it doesn't, you have retired a claim honestly. ⚡ Aetherforce custom: does NOT count towa",
     "steps": "Tune a neutral pendulum's string length to a battery's positive pole until you feel the pull. Then run two arms: 20 OPEN trials where you know each battery's polarity (the positive control — can you produce the signal at all?), then 40 BLIND trials where a second person flips a coin, hides each battery in an opaque container, and codes it without you seeing. Report pull or no-pull in writing before each container is opened, unblind only after the last number, and score hits against a 50% chance baseline with a binomial test. Add a 10-trial sham block of empty containers to catch false positives. Target: open arm >=16/20 AND blind arm >=27/40 at p<0.05 AND sham false positives <=2/10 — or an honest refutation of the claim at home scale.",
     "subjects": [
      "Science",
      "Health",
      "Community"
     ],
     "passFail": "PASS: open arm >=16/20 (80%) AND blind arm >=27/40 (67.5%) with binomial p<0.05 one-tailed (chance 0.5) AND sham false-positive rate <=2/10, and the direction repeats in a second run. FAIL: open arm >=16/20 (operator demonstrably can produce the signal open) AND blind hit rate within chance (16-24/40, p>0.05). INCONCLUSIVE: open arm <16/20 (operator cannot produce the signal even open - the blind ",
     "sourceNote": "sources/video/2026-09-21-biogeometry-neutral-pendulum-testing (video record — Vesica Institute, 'Learning to Test with the Neutral Pendulum')",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "vitality"
    }
   ]
  },
  {
   "id": "community",
   "name": "Community",
   "emoji": "🤝",
   "subtitle": "people, plants & group experiments",
   "cards": [
    {
     "id": "2026-09-21-psi-track-dowsing",
     "date": "2026-09-21",
     "title": "Psi-Track Night",
     "emoji": "🧭",
     "guild": "Aetherforce — Community",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "In 1987 a Swedish artist noticed that when he thought hard about a chair across the yard, his father could follow a line to it with a dowsing rod. Seven years later a physicist and a psychiatrist ran that as a real experiment: 40 double-blind trials across three years, a hidden object in a field, a sender who didn't know where it was, a dowser who didn't either — and they found the object 32 times. Their paper won a prize from the Society for Psychical Research. It has never been independently repeated, and that is the whole point of this quest. Your neighborhood becomes the replication: one p",
     "steps": "Pick a clean open area at least 30 × 30 m and sweep the whole thing with a dowsing rod first, so you know nothing there already triggers it. Define 'hit' before you start (say, within 2 m of the object) and work out the chance rate from your area and radius. Then run at least 10 trials: the hider places a small personal object, records the true spot, seals it in an envelope and leaves; the sender stands at a marked spot, concentrates on the object for a fixed time, and creates the track; the dowser — who must never know where the object is — works in widening circles from the sending spot, marks the rod reactions, follows the line, and declares a final location; the scorer measures the distance and writes it down without opening the envelope. Rotate roles between people across trials, re-randomize the hiding spot every time, and unseal the key only after all 10 are scored. Measurable outcome: a hit rate at least 2× the computed chance rate, with mean distance error well below a random guess, replicating in a second block of 10 trials with roles rotated = the track is real on your field; hit rate at chance, or dowsers tracking a fixed direction instead of the object = the claim is r",
     "subjects": [
      "Science",
      "Community",
      "Self-Reliance"
     ],
     "passFail": "PASS: blind hit rate ≥ 2× the computed chance rate AND mean distance error significantly below the random-guess baseline AND the result replicates in a second block of ≥ 10 trials with roles rotated and locations re-randomized | FAIL: hit rate at or below chance, or distance error no better than random, or dowsers tracking a systematic direction (e.g. always toward the sending spot) instead of the",
     "sourceNote": "translations/2026-09-18-psi-track-dowsing-sweden-sv.md — 'Psi-track (Psi-spåret),' the Swedish account of Göte Andersson, Jens A. Tellefsen and Nils-Olof Jacobson's double-blind experiments (paranormal.se topic 664, from PSSPR no. 15 / Sökaren no. 3, 1994), including the Imich Prize citation from th",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "community"
    },
    {
     "id": "2026-09-12-kolisko-group-steigbild",
     "date": "2026-09-12",
     "title": "Group Steigbild Night",
     "emoji": "🌕",
     "guild": "Aetherforce — Community Living",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test the contested Kolisko claim as a neighborhood team: do metal-salt 'rising pictures' made the same evening in different homes resemble each other more than pictures from different evenings? Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Recruit 1-3 neighbor households. Each household runs the same capillary dynamolysis procedure on the same 4 evenings (2 near a full/new moon or Moon-planet conjunction, 2 control): silver nitrate (or iron sulphate) solution rising up filter paper, dried, photographed under consistent light. Blind raters sort all photos by visual similarity. Measurable outcome: same-evening photos cluster together at 1.5x chance rate or better, replicating across raters, supports the claim; at/below chance refutes it.",
     "subjects": [
      "Science",
      "Community",
      "Self-Reliance"
     ],
     "passFail": "PASS: same-evening photo pairs grouped by >=3 blind raters at >=1.5x chance, replicating in a second 4-evening round. FAIL: clustering at/below chance, or raters cluster by household instead of evening. INCONCLUSIVE: single household, <3 raters, or non-replicating 1.0-1.5x result.",
     "sourceNote": "doc:3135 (Lili Kolisko, Working With the Stars in Earthly Substance, rexresearch full text)",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "community"
    }
   ]
  }
 ]
};
