/* Quest cards feed — auto-generated by build_village_quest_feed.py (living-library quest-queue). Do not edit by hand. */
const QUEST_CARDS = {
 "generated": "2026-09-17",
 "source": "living-library quest-queue (Engine of Practicality)",
 "note": "Auto-generated. A quest card is a TEST of a claim, not an endorsement. Proposed cards are visible here before merging into the Quest Board.",
 "benches": [
  {
   "id": "viktor-vortex",
   "name": "Viktor Vortex",
   "emoji": "🌀",
   "subtitle": "water, flow & Schauberger's legacy",
   "cards": [
    {
     "id": "2026-09-15-dodonov-ether-vortex",
     "date": "2026-09-15",
     "title": "Dodonov Ether Vortex Test",
     "emoji": "🌀",
     "guild": "Aetherforce — Woodland Care",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Demonstrate the formation of an ether vortex in water using a wooden spiral corrector (Dodonov corbio). Test whether vertical ether flows entering Earth from space can be detected through ink vortex formation. Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Fill a clear glass jar with still water. Add a few drops of dark ink through a tube to the bottom, letting it spread across the bottom. Place a wooden spiral-grooved corrector (cylinder with helical grooves) on top of the jar. Photograph the ink distribution every 15 minutes for 90 minutes. Measurable outcome: ink gathers toward center forming a vortex column extending upward.",
     "subjects": [
      "Science",
      "Woodland Care",
      "Self-Reliance"
     ],
     "passFail": "PASS: Ink forms central vortex column within 90 minutes, persists while corrector is present, dissipates within 15 minutes of removal. FAIL: Ink remains evenly spread or forms random patterns with no central convergence. INCONCLUSIVE: Weak central gathering that doesn't form clear column.",
     "sourceNote": "atsyukovsky-book5-ether-vortex",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-13-cold-vortex-germination",
     "date": "2026-09-13",
     "title": "Cold Vortex Water Germination Test",
     "emoji": "🌱",
     "guild": "Aetherforce — Water",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "Test Schauberger's +4°C water-vitality claim on real seeds: three trays, one watered with cold vortexed water, two controls. Germination is the verdict. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Schauberger claimed water near +4°C gains biological quality ('positive temperature movement'). Test it: sow 25 radish seeds in each of 3 trays. Arm A gets water vortex-stirred then chilled to 4°C; Arm B gets the same water chilled but unstirred; Arm C gets room-temperature water. Water daily with equal volumes for 10 days. Record germination count daily. Target: measurable difference between arms, with Arm A ≥ controls if the claim holds — or an honest refutation if it doesn't.",
     "subjects": [
      "Science",
      "Gardening",
      "Water"
     ],
     "passFail": "PASS: cold-vortex arm germination ≥ room control by ≥15 points AND ≥ cold-unstirred control. FAIL: cold-vortex arm underperforms room control, or matches the cold-unstirred arm (effect is temperature, not vortex). INCONCLUSIVE: <40% germination in all arms or <5-point spread.",
     "sourceNote": "translation:2026-09-11-compendium-of-vortex-physics-schauberger-de (p.88-89, positive temperature movement)",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-13-moonlight-germination",
     "date": "2026-09-13",
     "title": "Moonlight Germination Test",
     "emoji": "🌙",
     "guild": "Aetherforce — Food",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "Moon planting is the oldest claim in the archive — and in 2023 a peer-reviewed study found real cellular changes from full moonlight. Test it yourself: two trays of seeds, one sleeping under the full moon, one in a dark box. The kitchen scale decides. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Sow 25 mustard or radish seeds in each of 2 trays. On the 3 nights around the next full moon, place both trays in a spot that receives direct moonlight — cover one tray with an opaque box from dusk to dawn. Same soil, same water, same daylight. Count germination daily; at day 10-12 cut and weigh all seedlings per tray. Target: moonlight tray at least 15% heavier than the dark tray if the 2023 finding holds at home scale — or an honest refutation of the lunar-planting lineage where it's strongest.",
     "subjects": [
      "Science",
      "Gardening",
      "Food"
     ],
     "passFail": "PASS: moonlight arm fresh mass ≥ dark arm by ≥15% AND germination ≥ dark arm. FAIL: moonlight arm ≤ dark arm on fresh mass. INCONCLUSIVE: moon blocked by clouds ≥2 of 3 nights, artificial light reached the trays, or germination <40% in both arms — rerun next full moon.",
     "sourceNote": "sources:steiner-roots-2026-09-13 (Nugget 1 — Singiri et al. 2023, Plants 12(5):1121)",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-11-ez-water-exclusion-zone",
     "date": "2026-09-11",
     "title": "EZ Water Exclusion Zone Test",
     "emoji": "💧",
     "guild": "Aetherforce — Water",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "Visualize Pollack's exclusion zone water at hydrophilic interfaces. Measure particle-free zone width and IR-driven growth. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Place a hydrophilic surface (Nafion sheet or treated glass) in water with microsphere suspension. Wait 15 minutes for particles to settle. Using a microscope (100-400×), observe the particle-free exclusion zone forming near the surface. Measure EZ width at 5 points and calculate average. Illuminate with IR lamp or sunlight for 20 minutes and remeasure. Target: EZ ≥100 μm baseline, ≥20% growth under IR.",
     "subjects": [
      "Science",
      "Water",
      "Biology"
     ],
     "passFail": "EZ width ≥100 μm visible AND ≥20% growth under IR illumination",
     "sourceNote": "scout:2026-09-04-scout-a-de-fr-es-ru-it-ja-zh#entry-9",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-10-vortex-jet-turbine",
     "date": "2026-09-10",
     "title": "Vortex Jet Turbine Energy Test",
     "emoji": "🌀",
     "guild": "Aetherforce — Power",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test Schauberger's 1930 jet-turbine claim: spiral vortex induction makes flowing water deliver more power than a straight pipe at the same head. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Mount a small DC water turbine generator ($20-40) at a fixed 1 m head. Run three intake configs, 5 runs each, alternating order: (A) straight 3-4cm pipe control, (B) same pipe with a jet restriction reducing to 1-1.5cm, (C) jet + spiral ribs or angled vanes inducing a vortex. Each run: record voltage and current into a fixed 10-50 ohm resistor load for 60s, time a bucket fill for flow rate (L/s), measure inlet vs outlet water temperature. Compute P = V·I per run. Measurable outcome: C beats A by >15% AND beats B by >10% beyond run-to-run spread, with flow not dropping enough to explain the gain = supports the vortex-efficiency claim; C within noise of B = spiral ribs add nothing at home scale; flow varying >10% between runs = inconclusive.",
     "subjects": [
      "Science",
      "Engineering",
      "Energy"
     ],
     "passFail": "C > A by >15% AND C > B (jet-only control) by >10% beyond noise = PASS; C ≈ B = FAIL (ribs add nothing); flow variance >10% or output <0.5 W = INCONCLUSIVE",
     "sourceNote": "translations/2026-09-09-schauberger-dynamic-hydroelectric-energy-es.md",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-09-hyperbolic-funnel-vortex",
     "date": "2026-09-09",
     "title": "Hyperbolic Funnel Vortex Aerator",
     "emoji": "🌀",
     "guild": "Aetherforce — Water",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "Build Walter Schauberger's hyperbolic funnel water vortex. Test aeration efficiency against control. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Construct a hyperbolic funnel (acrylic or glass, 10-15cm upper diameter, 1-2cm lower outlet, 20-30cm height) following Walter Schauberger's profile. Establish a stable free-surface water vortex. Measure dissolved oxygen before and after 30 minutes of operation. Calculate SOTR (Standard Oxygen Transfer Rate). Compare to bubble diffuser control if available. Target: SOTR exceeds 2× control at same power input.",
     "subjects": [
      "Science",
      "Engineering",
      "Water"
     ],
     "passFail": "SOTR > 2× control OR stable vortex with visible air entrainment in Regime B",
     "sourceNote": "scout:2026-08-29-scout-b-es-fr-zh#entry-4",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    },
    {
     "id": "2026-09-06-wasserwirbler",
     "date": "2026-09-06",
     "title": "Build the Wasserwirbler (Vortexer)",
     "emoji": "🌀",
     "guild": "Plumbing and Hot Water",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Build a water vortexer and test the Schauberger water claims (temp + taste).",
     "steps": "Build a hyperbolic funnel with a threaded outlet; pour water through in a centripetal spin. Run the blind temperature test (A) and taste test (B) from dossier 001. Record all numbers + photos.",
     "subjects": [
      "Science",
      "Engineering"
     ],
     "passFail": "Temp: consistent ≥0.3°C difference vortexed vs control (4/5 trials). Taste: vortexed picked as 'softer/rounder' ≥8/10 blind.",
     "sourceNote": "scout find 2026-09-05 #9 (Orpanit, 'Viktor Schauberger und der Wasserwirbler') + Schauberger 1951 Luxembourg patent 31,480 (translation)",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "viktor-vortex"
    }
   ]
  },
  {
   "id": "eeman-circuit",
   "name": "Eeman Circuit",
   "emoji": "⚡",
   "subtitle": "electricity, biofields & subtle energy tests",
   "cards": [
    {
     "id": "2026-09-17-earth-energy-grid-instrument-scan",
     "date": "2026-09-17",
     "title": "Earth-Energy Grid Instrument Scan",
     "emoji": "🧭",
     "guild": "Aetherforce — Earthworks",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "The geobiology tradition says the Earth is wrapped in a grid of 'earth radiation' lines — the Hartmann grid, running N-S and E-W about 2 m apart. Every test of it so far used dowsing rods. No one has ever found it with an instrument. You will. Fix a phone in a cardboard jig (fixed height, fixed orientation), open a free magnetometer app, and walk a 1 m grid across two rooms and your yard, logging the magnetic field (µT) at every point. Repeat three times, average the runs, and plot field vs position. Measurable outcome: a repeating pattern at ~2 m spacing whose amplitude rises clearly above yo",
     "steps": "Build a fixed-orientation cardboard jig for a phone, open a free magnetometer app, and record the noise floor (30 still readings). Lay a 1 m measurement grid across two rooms and the yard, log the magnetic field (µT) at each point, and repeat each grid 3 times. Average the passes and plot field vs position. Measurable outcome: a repeating ~2 m-period structure present in ≥2 of 3 averaged runs with amplitude ≥3× the noise floor = the grid is a real magnetic structure in your home; no structure above noise = the tradition's instrument-detection gap stays open, honestly.",
     "subjects": [
      "Science",
      "Measurement",
      "Observation"
     ],
     "passFail": "PASS: repeating ~2 m-period structure in ≥2 of 3 averaged runs AND amplitude ≥3× measured noise floor | FAIL: no periodic structure above noise in any room (honest negative, Skeptic's Star) | INCONCLUSIVE: structure below threshold or <3 passes",
     "sourceNote": "translations/2026-08-29-hotie-viviane-broceliande-fr-en.md",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-14-bladeless-tesla-turbine",
     "date": "2026-09-14",
     "title": "Bladeless Tesla Turbine Static Electricity Test",
     "emoji": "⚡",
     "guild": "Aetherforce — Power",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test the 2026 bladeless Tesla turbine claim: compressed air + electrostatic injection generates usable electrical output beyond either alone. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Build a bladeless Tesla turbine (5-10 smooth disks, 1-2 mm spacing) on low-friction bearings. Connect compressed air (2-4 bar) via tangential nozzle at disk edges. Add electrostatic generator (10-50 kV) with electrode injecting charges into airflow upstream of turbine. Wire electrical pickup (brushes or induction coil) to multimeter and oscilloscope. Run three configs, 5 runs each, alternating order: (A) air only, (B) electrostatic only, (C) combined. Each run: log voltage, current, RPM (tachometer), airflow (anemometer), ambient static before/after. Measurable outcome: C produces V > 10V and I > 0.1A while A and B produce negligible output, with RPM 6,800-10,100 and airflow 240-360 m/s = supports electrostatic conversion claim; C within noise of A or B = combined effect does not replicate at home scale; RPM/airflow significantly below range = inconclusive (mechanical issues).",
     "subjects": [
      "Science",
      "Engineering",
      "Energy"
     ],
     "passFail": "C produces V > 10V and I > 0.1A while A and B produce negligible output, with RPM 6,800-10,100 and airflow 240-360 m/s = PASS; C within noise of A or B = FAIL (no combined effect); RPM/airflow below range = INCONCLUSIVE",
     "sourceNote": "sources/2026-08-29-scout-b-es-fr-zh.md",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-14-orgone-accumulator-tot",
     "date": "2026-09-14",
     "title": "Orgone Accumulator Temperature Test",
     "emoji": "🌡️",
     "guild": "Aetherforce — Oddball",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test whether a Reich orgone accumulator (layered steel wool + organic material) produces a measurable temperature difference beyond convection. The discriminating experiment Einstein himself requested in 1941. Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Build a 3-ply orgone accumulator (steel wool + cotton/wool layers, ~30cm cube) and a thermodynamically-matched solid-wall control box. Install differential thermocouples in both. Log interior vs ambient temperature every 5 minutes for 30 days. Third party blinds the sensor labels. Measurable outcome: ORAC exceeds control by ≥0.1°C on average, with weather-state correlation.",
     "subjects": [
      "Science",
      "Health",
      "Self-Reliance"
     ],
     "passFail": "PASS: ORAC ≥0.1°C warmer than control, correlates with weather (higher in clear/dry), second-harmonic present. FAIL: no significant difference, or control warmer. INCONCLUSIVE: small difference that doesn't reach significance.",
     "sourceNote": "dossier-017-orgone-accumulator-tot",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-12-eeman-sleep-quality",
     "date": "2026-09-12",
     "title": "Sleep Quality Biofield Test",
     "emoji": "🌙",
     "guild": "Aetherforce — Natural Medicine",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test whether the Eeman self-connecting copper circuit (no power) improves sleep quality when used before bed. Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Build an Eeman circuit (insulated copper wire, head band, hand/foot contacts, ~$10). Use it for 15 minutes before bed on 7 nights (randomly selected). Compare sleep quality (duration, wake-ups, morning alertness) vs 7 control nights (no circuit). Log each morning. Measurable outcome: sleep quality score difference ≥15% supports the claim.",
     "subjects": [
      "Science",
      "Health",
      "Self-Reliance"
     ],
     "passFail": "PASS: circuit nights ≥15% higher sleep quality score vs control, replicates across ≥2 testers. FAIL: no meaningful difference (within 5%). INCONCLUSIVE: small difference that doesn't replicate.",
     "sourceNote": "dossier-012-eeman-sleep-quality",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-12-form-waves-space-harmony",
     "date": "2026-09-12",
     "title": "Form Waves Space Harmony Test",
     "emoji": "🔷",
     "guild": "Aetherforce — Natural Building",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Apply sacred geometry principles to understand how forms affect spaces. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Test whether geometric forms (Flower of Life, golden spiral, pyramid) measurably change your energy field distance as detected by dowsing rods. Use a blank paper control. Report baseline, form, and control distances.",
     "subjects": [
      "Science",
      "Geometry",
      "Observation"
     ],
     "passFail": "PASS: Form distance ≥20% larger than baseline AND control. FAIL: No consistent difference (within 10%).",
     "sourceNote": "translations/2026-08-29-ondes-de-forme-vibratis-fr-en.md",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-10-eeman-animal-calm",
     "date": "2026-09-10",
     "title": "Eeman Circuit for Animal Calm",
     "emoji": "🐾",
     "guild": "Animal Care",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test whether the Eeman circuit calms animals (pets/livestock) — blind behavior observation.",
     "steps": "Build the Eeman circuit (same as human test — ~$10 copper wire). Test on one animal (dog, cat, horse, chicken) using the blind protocol from dossier 006: circuit vs sham, 5 sessions, observe restlessness + breathing + vocalizations. Record all observations + photos.",
     "subjects": [
      "Science",
      "Animal Care"
     ],
     "passFail": "Circuit shows calmer behavior vs sham (same direction ≥4/5 sessions, delta ≥2 restlessness points or ≥3 breaths/30s).",
     "sourceNote": "dossier 002 (Eeman human circuit) + biofield tradition extension",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-10-electrostatic-energy-test",
     "date": "2026-09-10",
     "title": "Electrostatic Energy Balance Test",
     "emoji": "⚡",
     "guild": "Aetherforce — Community",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test whether electrostatic machines can extract vacuum energy, as claimed by the Methernita community's 750 kW Testatika system running since 1980.",
     "steps": "Build or buy a Wimshurst machine ($50-100). Crank for 60 seconds to charge a capacitor bank (20-40µF, 400V). Close switch to LED array. Time how long LED stays lit (>50% brightness). Calculate energy: E = ½CV². Compare output to cranking input work. Measurable outcome: LED illumination time > 66 seconds (10% above cranking duration) AND calculated output > input by >10% = supports claim; LED time ≤ 60s or output ≤ input = refutes claim.",
     "subjects": [
      "Science",
      "Engineering",
      "Energy"
     ],
     "passFail": "LED illumination >66s AND calculated output > input by >10% = PASS; LED ≤60s or output ≤ input = FAIL; machine fails to charge = INCONCLUSIVE",
     "sourceNote": "translations/2026-09-04-shipov-torsion-fields-ru-en.md",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-09-blind-geopathic-mapping",
     "date": "2026-09-09",
     "title": "Blind Geopathic Zone Mapping",
     "emoji": "📡",
     "guild": "Aetherforce — Nest",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural",
      "urban"
     ],
     "status": "proposed",
     "desc": "Can two people walking the same room with dowsing rods find the SAME earth-energy lines without seeing each other's maps? The geobiology tradition (Hartmann grid, Curry lines) says yes; the 1991 Kassel test says no. Your family settles it for your own home — with numbers. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Bend two sets of L-rods from coat hangers (~$5). Two family members each map the SAME room independently — wherever the rods cross, record the position by tape measure from two walls. Then both map a second room. A referee (great kid job) overlays the maps: same-room agreement vs cross-room agreement (the chance baseline). Run 3 sessions. Measurable outcome: same-room agreement ≥70% AND ≥25 points above the cross-room chance baseline = the lines are real for your home; agreement at chance = the rods found nothing shared, honestly retire the advice.",
     "subjects": [
      "Science",
      "Observation",
      "Family"
     ],
     "passFail": "Same-room agreement ≥70% across ≥3 sessions AND ≥25 points above cross-room chance baseline (PASS) | within 10 points of chance (FAIL — honest negative, Skeptic's Star)",
     "sourceNote": "scout:2026-08-30-scout-b-de-ru#entry-1",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    },
    {
     "id": "2026-09-08-tesla-radiant-receiver",
     "date": "2026-09-08",
     "title": "⚡ Aetherforce · Homesteading complement — Build the Radiant Energy Receiver",
     "emoji": "⚡",
     "guild": "Aetherforce — Power",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Build Tesla's 1901 radiant energy receiver — an elevated insulated plate charging a capacitor to ground — and measure what the sky actually gives you. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault",
     "steps": "Mount an insulated metal plate 3-5 m up on a NON-metal pole, wire it through a film capacitor to a ground rod, and measure voltage at 0/5/10/15 min across 5+ sessions (morning/noon/night, clear/overcast). Then wrap the plate in grounded foil as the control and repeat. PASS: receiver reads ≥10× the shielded control in ≥4/5 sessions. Storms: always disconnect and ground the antenna first.",
     "subjects": [
      "Science",
      "Engineering"
     ],
     "passFail": "Receiver accumulates charge ≥10× above shielded control, same direction in ≥4/5 sessions → collection confirmed (mechanism unresolved); compute stored energy ½CV² and report honest micro-watt scale. No accumulation above control → does not replicate at home scale; log as refuted.",
     "sourceNote": "translation 2026-09-03-tesla-patents-radiant-energy-fr (Tesla radiant energy patent schematics analysis, Lindemann compilation, FR→EN) + scout find 2026-08-26-a #2",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "eeman-circuit"
    }
   ]
  },
  {
   "id": "kitchen-lab",
   "name": "Kitchen Lab",
   "emoji": "🥚",
   "subtitle": "food, fermentation & living processes",
   "cards": [
    {
     "id": "2026-09-16-korschelt-aether-ray-ripening",
     "date": "2026-09-16",
     "title": "Korschelt Aether-Ray Ripening Test",
     "emoji": "🍷",
     "guild": "Aetherforce — Commerce",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test Oskar Korschelt's 1892 claim that a galvanic-element 'aether ray' apparatus ripens sealed wine and spirits — improving their taste — and promotes plant growth. Run a blind triangle test to see whether the taste change survives when the taster doesn't know which bottle was treated. Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Build a simplified Korschelt ray apparatus: a sheet-metal tube with two discs ~4 cm apart connected to a low-voltage DC source, plus a wire spiral along the tube. Split 6 matched bottles of a young wine or spirit into treated (3, inside the tube, energized 2-7 days) and control (3, same room, unpowered). Then run a blind triangle test: 9 trials, each with 3 cups (two from one bottle, one from the other), taster identifies the odd cup and states a preference. Measurable outcome: taster correctly identifies the odd cup in at least 6 of 9 trials (p<0.05). Optional plant arm: run the Fig. 10 star-disc apparatus under one of two matched potted plants for 14 days and compare new shoot growth.",
     "subjects": [
      "Science",
      "Commerce",
      "Food",
      "Self-Reliance"
     ],
     "passFail": "PASS: Taster identifies the odd cup in >=6 of 9 blind triangle trials (p<0.05) AND prefers the treated sample in a majority of trials; plant arm shows >20% greater new shoot growth than control, repeated in a second run. FAIL: <=3 of 9 correct (chance) — taste effect not detectable blind. INCONCLUSIVE: 4-5 of 9 correct, or effect in one beverage type only, or plant difference within measurement no",
     "sourceNote": "korschelt-1892-aether-ray-ripening",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "kitchen-lab"
    },
    {
     "id": "2026-09-11-egg-fermentation-vessel",
     "date": "2026-09-11",
     "title": "Egg-Shaped Fermentation Test",
     "emoji": "🥚",
     "guild": "Aetherforce — Food",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test whether egg-shaped fermentation vessels produce superior outcomes compared to cylindrical vessels. Schauberger claimed the egg form is ideal for water storage and that fermentation at +4° to +9°C with light exclusion produces higher-grade processes. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Prepare identical sauerkraut batches in an egg-shaped container and a cylindrical container. Track pH daily for 14 days. Record: time to target pH (≤3.7), visual fermentation activity, mold presence, and final taste. Conduct blind taste test with 3+ family members. Report: vessel type used, pH log, photos, taste scores, and whether egg vessel showed measurable advantage.",
     "subjects": [
      "Fermentation",
      "Food Preservation",
      "Experimental Science"
     ],
     "passFail": "PASS if egg vessel reaches target pH faster OR shows fewer off-flavors OR wins blind taste test. FAIL if no measurable difference or cylinder performs better. INCONCLUSIVE if both fail to ferment properly.",
     "sourceNote": "translations/2026-09-09-compendium-of-vortex-physics-de.md",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "kitchen-lab"
    }
   ]
  },
  {
   "id": "form-shelter",
   "name": "Form & Shelter",
   "emoji": "🏠",
   "subtitle": "natural building & shape effects",
   "cards": [
    {
     "id": "2026-09-13-wood-acoustic-resonance",
     "date": "2026-09-13",
     "title": "Wood Acoustic Resonance Test",
     "emoji": "🪵",
     "guild": "Aetherforce — Round Wood",
     "tier": "sand",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test whether wood grain density affects acoustic resonance. ⚡ Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Collect 3-5 wood samples from different trees or species. Count annual rings per inch. Tap each sample with consistent force and record the sound. Use a free sound analyzer app to measure sustain time (how long the note rings). Compare: Does tighter grain correlate with longer sustain?",
     "subjects": [
      "Science",
      "Woodworking",
      "Observation"
     ],
     "passFail": "PASS: Sample with tightest grain shows ≥20% longer sustain than sample with widest grain. FAIL: No consistent correlation between grain density and sustain time.",
     "sourceNote": "translations/2026-09-09-schauberger-water-blood-of-earth-de.md",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "form-shelter"
    }
   ]
  },
  {
   "id": "community",
   "name": "Community",
   "emoji": "🤝",
   "subtitle": "people, plants & group experiments",
   "cards": [
    {
     "id": "2026-09-12-kolisko-group-steigbild",
     "date": "2026-09-12",
     "title": "Group Steigbild Night",
     "emoji": "🌕",
     "guild": "Aetherforce — Community Living",
     "tier": "straw",
     "biomes": [
      "suburb",
      "rural"
     ],
     "status": "proposed",
     "desc": "Test the contested Kolisko claim as a neighborhood team: do metal-salt 'rising pictures' made the same evening in different homes resemble each other more than pictures from different evenings? Aetherforce custom: does NOT count toward Permies badges (earn it here). Source: Aetherforce Knowledge Vault.",
     "steps": "Recruit 1-3 neighbor households. Each household runs the same capillary dynamolysis procedure on the same 4 evenings (2 near a full/new moon or Moon-planet conjunction, 2 control): silver nitrate (or iron sulphate) solution rising up filter paper, dried, photographed under consistent light. Blind raters sort all photos by visual similarity. Measurable outcome: same-evening photos cluster together at 1.5x chance rate or better, replicating across raters, supports the claim; at/below chance refutes it.",
     "subjects": [
      "Science",
      "Community",
      "Self-Reliance"
     ],
     "passFail": "PASS: same-evening photo pairs grouped by >=3 blind raters at >=1.5x chance, replicating in a second 4-evening round. FAIL: clustering at/below chance, or raters cluster by household instead of evening. INCONCLUSIVE: single household, <3 raters, or non-replicating 1.0-1.5x result.",
     "sourceNote": "doc:3135 (Lili Kolisko, Working With the Stars in Earthly Substance, rexresearch full text)",
     "vaultUrl": "https://focusingpulse.github.io/AFLinks/",
     "aetherforceUrl": "https://www.aetherforce.energy",
     "bench": "community"
    }
   ]
  }
 ]
};
