/* ============================================================
 * THE VILLAGE — THE THORNS WELCOME
 *
 * "Permaculture Thorns" is Paul Wheaton's work-in-progress book
 * about the difficult realities of building permaculture community
 * (draft eBook on Permies; Podcasts 754 & 755, Aug 2026, with
 * Kay, Julia, Samantha and Ash Jackson). His core stance: community
 * is more important than productivity, and the things that prick
 * you are not failures — they are the syllabus.
 *
 * This module turns that into a game-layer practice:
 *   NAME THE THORN BEFORE IT STINGS.
 * Every thorn card pairs an honest description (grounded in Paul's
 * actual discussions) with a Chris Voss negotiation move — labeling,
 * accusation audit, calibrated questions, no-oriented questions,
 * tactical empathy — so families learn to meet challenges out loud
 * instead of discovering them the hard way.
 *
 * i18n: en / es / fr blocks. Add a language by copying a block,
 * translating, and changing the key.
 * NOTE: this file is generated by /tmp/gen_thorns.py — edit the generator.
 * ============================================================ */

const THORNS_I18N =
{
  "en": {
    "title": "The Thorns Welcome",
    "tag": "Before you build community — or join one — read this. Paul Wheaton calls the hard parts of community living 'Permaculture Thorns': the things nobody warns you about, the moments that make you want to leave. This is the honest version, so you can go in with your eyes open.",
    "audit": "I know this list can sound like a pile of warnings. It is not a warning — it is a map. A thorn is not a failure. It is the syllabus.",
    "progress": "Thorns named",
    "what": "What it is",
    "shows": "How it shows up",
    "nameIt": "Name it",
    "meetIt": "Meet it",
    "voss": "Voss move",
    "of": "of",
    "book": "Read Paul's in-progress book, 'Permaculture Thorns' (draft eBook)",
    "podcast1": "Podcast 754 — The Challenges of Building Community, Part 1",
    "podcast2": "Podcast 755 — The Challenges of Building Community, Part 2",
    "tap": "Tap a thorn to name it — naming is the first move."
  },
  "es": {
    "title": "La Bienvenida de las Espinas",
    "tag": "Antes de construir comunidad — o unirte a una — lee esto. Paul Wheaton llama 'Espinas de la Permacultura' a las partes difíciles de vivir en comunidad: las cosas que nadie te advierte, los momentos que te hacen querer irte. Esta es la versión honesta, para que entres con los ojos abiertos.",
    "audit": "Sé que esta lista puede sonar a montón de advertencias. No es una advertencia — es un mapa. Una espina no es un fracaso. Es el programa de estudios.",
    "progress": "Espinas nombradas",
    "what": "Qué es",
    "shows": "Cómo aparece",
    "nameIt": "Nómbrala",
    "meetIt": "Enfréntala",
    "voss": "Movimiento Voss",
    "of": "de",
    "book": "Lee el libro en progreso de Paul, 'Permaculture Thorns' (borrador eBook)",
    "podcast1": "Podcast 754 — Los Desafíos de Construir Comunidad, Parte 1",
    "podcast2": "Podcast 755 — Los Desafíos de Construir Comunidad, Parte 2",
    "tap": "Toca una espina para nombrarla — nombrar es el primer movimiento."
  },
  "fr": {
    "title": "L'Accueil des Épines",
    "tag": "Avant de bâtir une communauté — ou d'en rejoindre une — lisez ceci. Paul Wheaton appelle les parties difficiles de la vie en communauté les « Épines de la Permaculture » : les choses que personne ne vous signale, les moments qui donnent envie de partir. Voici la version honnête, pour entrer les yeux ouverts.",
    "audit": "Je sais que cette liste peut ressembler à un tas d'avertissements. Ce n'est pas un avertissement — c'est une carte. Une épine n'est pas un échec. C'est le programme.",
    "progress": "Épines nommées",
    "what": "Ce que c'est",
    "shows": "Comment ça se manifeste",
    "nameIt": "Nommez-la",
    "meetIt": "Affrontez-la",
    "voss": "Geste de Voss",
    "of": "sur",
    "book": "Lisez le livre en cours de Paul, « Permaculture Thorns » (eBook brouillon)",
    "podcast1": "Podcast 754 — Les Défis de Construire une Communauté, Partie 1",
    "podcast2": "Podcast 755 — Les Défis de Construire une Communauté, Partie 2",
    "tap": "Touchez une épine pour la nommer — nommer est le premier geste."
  }
};

/* The ten Thorns — grounded in Paul Wheaton's actual book work and
 * Podcasts 754/755. Each carries its Voss move for meeting it. */
const THORNS_LIST =
[
  [
    "two-week",
    "🗓️",
    [
      "The Two-Week Thorn",
      "The newcomer who wants to change everything. Wheaton Labs has a guideline: new boots 'go with the flow' for the first two weeks, because the first instinct on arrival is often to announce that everything is being done wrong — willow feeders, the compost, the whole system.",
      "You arrive full of ideas, and every one feels politely ignored.",
      "It sounds like my good ideas are being dismissed. I want to be heard.",
      "Write the ideas down. Earn the right to be heard by doing the work first — then your voice lands harder.",
      "Say the hard thing about yourself first, so nobody has to.",
      "Accusation Audit"
    ],
    [
      "La Espina de las Dos Semanas",
      "El recién llegado que quiere cambiarlo todo. En Wheaton Labs hay una guía: los nuevos boots 'siguen la corriente' las dos primeras semanas, porque el primer instinto al llegar suele ser anunciar que todo se está haciendo mal — los alimentadores de sauce, el compost, todo el sistema.",
      "Llegas lleno de ideas, y cada una parece cortésmente ignorada.",
      "Suena como si mis buenas ideas fueran rechazadas. Quiero que me escuchen.",
      "Anota las ideas. Gana el derecho a ser escuchado haciendo el trabajo primero — así tu voz cala más hondo.",
      "Di tú mismo lo difícil primero, para que nadie tenga que decirlo.",
      "Auditoría de Acusación"
    ],
    [
      "L'Épine des Deux Semaines",
      "Le nouveau venu qui veut tout changer. Wheaton Labs a une règle : les nouveaux boots « suivent le courant » les deux premières semaines, car le premier réflexe à l'arrivée est souvent d'annoncer que tout est mal fait — les mangeoires à saules, le compost, tout le système.",
      "Vous arrivez plein d'idées, et chacune semble poliment ignorée.",
      "On dirait que mes bonnes idées sont rejetées. Je veux être écouté.",
      "Écrivez vos idées. Gagnez le droit d'être écouté en faisant d'abord le travail — votre voix portera plus loin.",
      "Dites d'abord vous-même le difficile, pour que personne n'ait à le dire.",
      "Audit d'Accusation"
    ]
  ],
  [
    "fairness",
    "🍳",
    [
      "The Fairness Thorn",
      "Who cooks, who cleans, whose turn to wash the dishes — the everyday ledger of shared life. At the Labs it shows up as 'project labor' versus 'nest labor' (the short-term care tasks: cooking, cleaning, shoveling snow, harvesting for the next few days).",
      "The same person is always at the sink, and the person who never cooks always has an opinion on dinner.",
      "It feels like the chores aren't fair. I'm carrying more than my share.",
      "Name the split out loud and don't let it curdle — a fair ledger beats a silent grudge every time.",
      "Name the feeling, and the person feels understood instead of attacked.",
      "Labeling"
    ],
    [
      "La Espina de la Justicia",
      "Quién cocina, quién limpia, a quién le toca lavar los platos — el libro diario de la vida compartida. En el Labs aparece como trabajo de 'proyecto' frente a trabajo de 'nido' (las tareas de cuidado a corto plazo: cocinar, limpiar, palear nieve, cosechar para los próximos días).",
      "La misma persona siempre está en el fregadero, y quien nunca cocina siempre tiene opinión sobre la cena.",
      "Siente que las tareas no son justas. Estoy cargando más de lo que me toca.",
      "Nombra el reparto en voz alta y no dejes que se agrie — un libro justo vence a un rencor silencioso siempre.",
      "Nombra el sentimiento y la persona se siente comprendida en vez de atacada.",
      "Etiquetado"
    ],
    [
      "L'Épine de l'Équité",
      "Qui cuisine, qui nettoie, à qui le tour de la vaisselle — le registre quotidien de la vie partagée. Aux Labs, ça apparaît comme travail de « projet » contre travail de « nid » (les soins à court terme : cuisiner, nettoyer, pelleter la neige, récolter pour les jours à venir).",
      "La même personne est toujours à l'évier, et celui qui ne cuisine jamais a toujours un avis sur le dîner.",
      "J'ai l'impression que les corvées ne sont pas justes. J'en porte plus que ma part.",
      "Nommez le partage à voix haute et ne le laissez pas aigrir — un registre juste bat toujours une rancune silencieuse.",
      "Nommez le sentiment, et la personne se sent comprise au lieu d'être attaquée.",
      "Étiquetage"
    ]
  ],
  [
    "judgment",
    "⚖️",
    [
      "The Judgment Thorn",
      "'Don't judge me' — but a community has to hold standards, and standards require judgment. Kay's point on the podcast: you have to have judgment to run a community, and people will call you an asshole for not compromising on them.",
      "Someone crosses a line and the moment you speak up, you're the bad guy for 'being judgmental'.",
      "This feels like being policed. I didn't sign up for judgment.",
      "Judgment is how standards survive. Say the standard out loud, plainly, and own that it's yours too.",
      "What does non-judgmental actually mean here — and how do we hold standards without it?",
      "Calibrated Question"
    ],
    [
      "La Espina del Juicio",
      "'No me juzgues' — pero una comunidad tiene que mantener estándares, y los estándares requieren juicio. El punto de Kay en el podcast: tienes que tener juicio para dirigir una comunidad, y te llamarán idiota por no ceder en ellos.",
      "Alguien cruza una línea y, en el momento en que hablas, tú eres el malo por 'ser juzgón'.",
      "Esto siente como vigilancia. No firmé para que me juzgaran.",
      "El juicio es como sobreviven los estándares. Di el estándar en voz alta, con claridad, y asume que también es tuyo.",
      "¿Qué significa realmente no juzgar aquí — y cómo mantenemos los estándares sin ello?",
      "Pregunta Calibrada"
    ],
    [
      "L'Épine du Jugement",
      "« Ne me jugez pas » — mais une communauté doit tenir des standards, et les standards exigent le jugement. Le point de Kay sur le podcast : il faut du jugement pour diriger une communauté, et on vous traitera de con pour ne pas céder sur eux.",
      "Quelqu'un franchit une ligne et, à l'instant où vous parlez, vous êtes le méchant pour être « jugeant ».",
      "Ça ressemble à de la surveillance. Je n'ai pas signé pour être jugé.",
      "Le jugement est ce qui fait survivre les standards. Dites le standard à voix haute, simple, et reconnaissez qu'il est aussi le vôtre.",
      "Que veut dire vraiment être non-jugeant ici — et comment tenir les standards sans ça ?",
      "Question Calibrée"
    ]
  ],
  [
    "rule-lawyer",
    "📜",
    [
      "The Rule-Lawyer Thorn",
      "Rules give bad guys traction. Kay's warning on the podcast: when you have rules, people become lawyers and work them in their favor — and the worst people are often the best at it. That's why the only rule at Permies.com is 'be nice'.",
      "Someone is technically in the right and everyone knows it's wrong. The loophole becomes the argument.",
      "I notice the rule is being used as a weapon instead of a guardrail.",
      "Keep rules few and standards high. When someone lawyers the rules, name the spirit, not the letter.",
      "Is it a bad idea to keep the rules few and simple? — a 'no'-oriented question opens the door.",
      "No-Oriented Question"
    ],
    [
      "La Espina del Abogado de Reglas",
      "Las reglas dan ventaja a los malos. La advertencia de Kay en el podcast: cuando hay reglas, la gente se vuelve abogada y las usa a su favor — y los peores suelen ser los mejores en eso. Por eso la única regla en Permies.com es 'sé amable'.",
      "Alguien está técnicamente en lo correcto y todos saben que está mal. El vacío legal se vuelve el argumento.",
      "Noto que la regla se usa como arma en vez de como protección.",
      "Pocas reglas y estándares altos. Cuando alguien manipula las reglas, nombra el espíritu, no la letra.",
      "¿Es mala idea mantener las reglas pocas y simples? — una pregunta orientada al 'no' abre la puerta.",
      "Pregunta Orientada al No"
    ],
    [
      "L'Épine de l'Avocat des Règles",
      "Les règles donnent de la prise aux méchants. L'avertissement de Kay sur le podcast : quand il y a des règles, les gens deviennent avocats et les utilisent à leur avantage — et les pires y sont souvent les meilleurs. C'est pourquoi la seule règle de Permies.com est « soyez gentil ».",
      "Quelqu'un est techniquement dans son droit et tout le monde sait que c'est mal. La faille devient l'argument.",
      "Je remarque que la règle sert d'arme au lieu de garde-fou.",
      "Gardez peu de règles et des standards élevés. Quand quelqu'un exploite les règles, nommez l'esprit, pas la lettre.",
      "Est-ce une mauvaise idée de garder les règles rares et simples ? — une question orientée « non » ouvre la porte.",
      "Question Orientée Non"
    ]
  ],
  [
    "nobility",
    "🛡️",
    [
      "The Nobility Filter",
      "You don't find out who is truly noble until the shit hits the fan — at which point about 5% step up. Paul wants a system that works with the top 60% and makes them more delightful more of the time. His best filter: make it easier to get out than to get in, so people self-select.",
      "The crisis hits and the people you expected to lead disappear — while the quiet ones quietly carry it.",
      "I'm realizing the test of character only shows up when things get hard.",
      "Design for self-selection: easy exits, honest asks. Then when the test comes, watch who moves — not who talks.",
      "Land the framing so hard they have to nod: the thorn isn't the crisis, it's the surprise.",
      "The 'That's Right' Moment"
    ],
    [
      "El Filtro de Nobleza",
      "No sabes quién es verdaderamente noble hasta que la mierda golpea el ventilador — y entonces solo un 5% da un paso al frente. Paul quiere un sistema que trabaje con el 60% superior y los haga más encantadores más a menudo. Su mejor filtro: que sea más fácil salir que entrar, para que la gente se autoseleccione.",
      "Llega la crisis y las personas que esperabas que lideraran desaparecen — mientras los callados cargan con todo en silencio.",
      "Me doy cuenta de que la prueba de carácter solo aparece cuando las cosas se ponen difíciles.",
      "Diseña para la autoselección: salidas fáciles, peticiones honestas. Cuando llegue la prueba, mira quién se mueve — no quién habla.",
      "Aterriza el marco tan fuerte que tengan que asentir: la espina no es la crisis, es la sorpresa.",
      "El Momento 'Eso es Correcto'"
    ],
    [
      "Le Filtre de Noblesse",
      "On ne sait pas qui est vraiment noble jusqu'à ce que ça tourne mal — et là, environ 5% se lèvent. Paul veut un système qui travaille avec les 60% du haut et les rend plus agréables plus souvent. Son meilleur filtre : rendre la sortie plus facile que l'entrée, pour que les gens se sélectionnent eux-mêmes.",
      "La crise arrive et ceux que vous attendiez comme leaders disparaissent — pendant que les discrets portent tout en silence.",
      "Je réalise que le test du caractère ne se montre que quand ça devient dur.",
      "Concevez pour l'auto-sélection : sorties faciles, demandes honnêtes. Quand le test vient, regardez qui bouge — pas qui parle.",
      "Posez le cadre si fort qu'ils doivent acquiescer : l'épine n'est pas la crise, c'est la surprise.",
      "Le Moment « C'est Exactement Ça »"
    ]
  ],
  [
    "captain",
    "👑",
    [
      "The Captain Dines Alone",
      "Ernie Wisner's line: the captain dines alone. Having the ultimate boss at the table restricts everyone — people stop talking freely. So Paul, who would love to join every meal, mostly doesn't. He joins taco Tuesday. Leadership has a cost, and the cost is chosen, not accidental.",
      "Everyone goes quiet when the leader walks in, and the leader feels it as loneliness.",
      "It feels like there's a distance between the leader and everyone else — on both sides.",
      "Name the distance for what it is: a structure, not a rejection. Make one small regular table where the boss is allowed to be human.",
      "The leader's loneliness and the group's restraint are the same thorn from two sides.",
      "Tactical Empathy"
    ],
    [
      "El Capitán Cena Solo",
      "La frase de Ernie Wisner: el capitán cena solo. Tener al jefe supremo en la mesa restringe a todos — la gente deja de hablar con libertad. Así que Paul, que amaría unirse a cada comida, mayormente no lo hace. Se une los martes de tacos. El liderazgo tiene un costo, y ese costo se elige, no es accidental.",
      "Todos se callan cuando el líder entra, y el líder lo siente como soledad.",
      "Siente que hay una distancia entre el líder y los demás — de ambos lados.",
      "Nombra la distancia por lo que es: una estructura, no un rechazo. Crea una pequeña mesa regular donde el jefe pueda ser humano.",
      "La soledad del líder y la contención del grupo son la misma espina desde dos lados.",
      "Empatía Táctica"
    ],
    [
      "Le Capitaine Dîne Seul",
      "La phrase d'Ernie Wisner : le capitaine dîne seul. Avoir le patron suprême à la table restreint tout le monde — les gens arrêtent de parler librement. Alors Paul, qui adorerait se joindre à chaque repas, ne le fait la plupart du temps. Il se joint au mardi des tacos. Le leadership a un coût, et ce coût est choisi, pas accidentel.",
      "Tout le monde se tait quand le leader entre, et le leader le ressent comme de la solitude.",
      "On sent une distance entre le leader et les autres — des deux côtés.",
      "Nommez la distance pour ce qu'elle est : une structure, pas un rejet. Faites une petite table régulière où le boss a le droit d'être humain.",
      "La solitude du leader et la retenue du groupe sont la même épine vue de deux côtés.",
      "Empathie Tactique"
    ]
  ],
  [
    "money",
    "💰",
    [
      "The Money Thorn",
      "The average Montana homestead is now over $1.5 million — you can't service that mortgage with homestead income. Samantha's answer: she doesn't try to make money from the land; the value is in the quality of food and life. The thorn is the expectation that this lifestyle pays like a job.",
      "The spreadsheet says it doesn't work. The dream doesn't fit on a mortgage calculator.",
      "I'm realizing the value here doesn't show up in the bank account.",
      "Count the yield in food eaten, skills grown, and life lived — not just dollars. Then the math changes.",
      "How is a family supposed to live this way without a million-dollar mortgage? — hand the question back, let it land.",
      "Calibrated Question"
    ],
    [
      "La Espina del Dinero",
      "El precio promedio de una propiedad en Montana supera el millón y medio de dólares — no puedes pagar esa hipoteca con ingresos de la tierra. La respuesta de Samantha: no intenta ganar dinero con la tierra; el valor está en la calidad de la comida y de la vida. La espina es la expectativa de que este estilo de vida paga como un trabajo.",
      "La hoja de cálculo dice que no funciona. El sueño no cabe en una calculadora de hipotecas.",
      "Me doy cuenta de que el valor aquí no aparece en la cuenta bancaria.",
      "Cuenta la cosecha en comida comida, habilidades crecidas y vida vivida — no solo en dólares. Entonces las matemáticas cambian.",
      "¿Cómo se supone que una familia viva así sin una hipoteca de un millón de dólares? — devuelve la pregunta, deja que aterrice.",
      "Pregunta Calibrada"
    ],
    [
      "L'Épine de l'Argent",
      "Le prix moyen d'une propriété au Montana dépasse 1,5 million de dollars — on ne paie pas cette hypothèque avec un revenu de ferme. La réponse de Samantha : elle n'essaie pas de gagner de l'argent avec la terre ; la valeur est dans la qualité de la nourriture et de la vie. L'épine est l'attente que ce mode de vie paie comme un emploi.",
      "Le tableur dit que ça ne marche pas. Le rêve ne tient pas dans un calculateur d'hypothèque.",
      "Je réalise que la valeur ici n'apparaît pas sur le compte en banque.",
      "Comptez le rendement en nourriture mangée, compétences apprises et vie vécue — pas seulement en dollars. Alors les maths changent.",
      "Comment une famille est-elle censée vivre ainsi sans hypothèque d'un million ? — rendez la question, laissez-la atterrir.",
      "Question Calibrée"
    ]
  ],
  [
    "cult-label",
    "🛸",
    [
      "The Cult-Label Thorn",
      "Local government gets paranoid about cults (Julia's experience forming a community). Paul's deadpan answer: 'We're a cult then? Fine — we're a cult.' The label comes from outside, and it comes for anyone who lives differently in a group.",
      "Your neighbors treat your community like a suspicious thing, and the word 'cult' gets thrown around.",
      "It sounds like people think we're a cult — and that's hard to hear.",
      "Don't argue the label. Live the counter-example: open doors, good food, honest work. The label dies of exposure.",
      "We're not a warning — we're a window. Let them look.",
      "Tactical Empathy"
    ],
    [
      "La Espina de la Etiqueta de Secta",
      "El gobierno local se pone paranoico con las sectas (la experiencia de Julia al formar una comunidad). La respuesta seca de Paul: '¿Entonces somos una secta? De acuerdo — somos una secta.' La etiqueta viene de fuera, y le llega a cualquiera que viva diferente en grupo.",
      "Tus vecinos tratan tu comunidad como algo sospechoso, y la palabra 'secta' se lanza al aire.",
      "Suena como si la gente pensara que somos una secta — y eso es difícil de oír.",
      "No discutas la etiqueta. Vive el contraejemplo: puertas abiertas, buena comida, trabajo honesto. La etiqueta muere de exposición.",
      "No somos una advertencia — somos una ventana. Deja que miren.",
      "Empatía Táctica"
    ],
    [
      "L'Épine de l'Étiquette de Secte",
      "Le gouvernement local devient paranoïaque à propos des sectes (l'expérience de Julia en formant une communauté). La réponse sèche de Paul : « Alors nous sommes une secte ? Très bien — nous sommes une secte. » L'étiquette vient de l'extérieur, et elle vient pour quiconque vit différemment en groupe.",
      "Vos voisins traitent votre communauté comme une chose suspecte, et le mot « secte » est lancé.",
      "On dirait que les gens pensent que nous sommes une secte — et c'est dur à entendre.",
      "Ne discutez pas l'étiquette. Vivez le contre-exemple : portes ouvertes, bonne nourriture, travail honnête. L'étiquette meurt d'exposition.",
      "Nous ne sommes pas un avertissement — nous sommes une fenêtre. Laissez-les regarder.",
      "Empathie Tactique"
    ]
  ],
  [
    "conditioned",
    "🧠",
    [
      "The Conditioned, Not Broken Thorn",
      "Paul's reframe when Ash asks if some people are too broken for community: 'programmed or conditioned' are better words than broken. Everyone carries programming — from school, family, the economy. The community's job is finding a way to overcome the conditioning together.",
      "Two people can look at the same situation and act from completely different programs — and clash without meaning to.",
      "I think we're both running old programs here, and they're colliding.",
      "Name the reflex, not the person. 'That's a program talking' beats 'you're wrong' every time.",
      "The hard part isn't bad people — it's the programming we all carry. Name it, and the loop can break.",
      "Tactical Empathy"
    ],
    [
      "La Espina del Condicionado, No Roto",
      "El replanteo de Paul cuando Ash pregunta si hay gente demasiado rota para la comunidad: 'programado o condicionado' son mejores palabras que roto. Todos cargamos programación — de la escuela, la familia, la economía. El trabajo de la comunidad es encontrar la manera de superar el condicionamiento juntos.",
      "Dos personas pueden mirar la misma situación y actuar desde programas completamente diferentes — y chocar sin querer.",
      "Creo que ambos estamos ejecutando programas viejos aquí, y están chocando.",
      "Nombra el reflejo, no a la persona. 'Eso es un programa hablando' vence a 'estás equivocado' siempre.",
      "Lo difícil no son las malas personas — es la programación que todos cargamos. Nómbrala y el bucle puede romperse.",
      "Empatía Táctica"
    ],
    [
      "L'Épine du Conditionné, Pas Cassé",
      "Le recadrage de Paul quand Ash demande si certaines personnes sont trop cassées pour la communauté : « programmé ou conditionné » sont de meilleurs mots que cassé. Tout le monde porte une programmation — de l'école, de la famille, de l'économie. Le travail de la communauté est de trouver un moyen de surmonter le conditionnement ensemble.",
      "Deux personnes peuvent regarder la même situation et agir depuis des programmes complètement différents — et se heurter sans le vouloir.",
      "Je crois que nous exécutons tous les deux de vieux programmes ici, et ils se heurtent.",
      "Nommez le réflexe, pas la personne. « C'est un programme qui parle » bat « vous avez tort » à chaque fois.",
      "Le difficile n'est pas les mauvaises personnes — c'est la programmation que nous portons tous. Nommez-la, et la boucle peut se briser.",
      "Empathie Tactique"
    ]
  ],
  [
    "winter",
    "❄️",
    [
      "The Winter Thorn",
      "Same faces, short days, the grind. New boots are told to let themselves take a break instead of sprinting to keep up with the veterans — because winter is when the community either gets real or wears thin. The season tests the gathering, not the garden.",
      "The enthusiasm of arrival fades into a gray routine, and small irritations get louder.",
      "It feels like the shine wore off, and now it's just the same faces and the same work.",
      "Winter is the syllabus in action. Adjust the pace, protect the rituals, and remember why you came.",
      "How am I supposed to keep showing up when the season is gray and the same four faces are all I see? — answer it together.",
      "Calibrated Question"
    ],
    [
      "La Espina del Invierno",
      "Mismas caras, días cortos, la rutina. A los nuevos boots se les dice que se permitan descansar en vez de correr para igualar a los veteranos — porque el invierno es cuando la comunidad se vuelve real o se desgasta. La estación prueba a la reunión, no al jardín.",
      "El entusiasmo de la llegada se desvanece en una rutina gris, y las pequeñas irritaciones se vuelven más fuertes.",
      "Siente que el brillo se apagó, y ahora solo quedan las mismas caras y el mismo trabajo.",
      "El invierno es el programa en acción. Ajusta el ritmo, protege los rituales y recuerda por qué viniste.",
      "¿Cómo se supone que siga apareciendo cuando la estación es gris y las mismas cuatro caras son todo lo que veo? — respóndanlo juntos.",
      "Pregunta Calibrada"
    ],
    [
      "L'Épine de l'Hiver",
      "Mêmes visages, jours courts, la routine. On dit aux nouveaux boots de se laisser le droit de faire une pause au lieu de courir pour suivre les vétérans — car l'hiver est le moment où la communauté devient réelle ou s'use. La saison teste le rassemblement, pas le jardin.",
      "L'enthousiasme de l'arrivée s'efface dans une routine grise, et les petites irritations deviennent plus fortes.",
      "On dirait que l'éclat est parti, et il ne reste que les mêmes visages et le même travail.",
      "L'hiver est le programme en action. Ajustez le rythme, protégez les rituels et rappelez-vous pourquoi vous êtes venus.",
      "Comment suis-je censé continuer à venir quand la saison est grise et que les mêmes quatre visages sont tout ce que je vois ? — répondez-y ensemble.",
      "Question Calibrée"
    ]
  ]
];

/* ---- Engine ---- */
let thornsLang = 'en';
try { thornsLang = (typeof lang !== 'undefined') ? lang : 'en'; } catch (e) {}

function thornsS(l) { return THORNS_I18N[l] || THORNS_I18N.en; }
function thornNamed(id) {
  try { const raw = localStorage.getItem('rpg_thorns_named'); if (raw) return JSON.parse(raw).includes(id); } catch (e) {}
  return false;
}
function thornCount() {
  try { const raw = localStorage.getItem('rpg_thorns_named'); if (raw) return (JSON.parse(raw) || []).length; } catch (e) {}
  return 0;
}
function thornToggle(id) {
  let arr = [];
  try { const raw = localStorage.getItem('rpg_thorns_named'); if (raw) arr = JSON.parse(raw) || []; } catch (e) {}
  if (arr.includes(id)) arr = arr.filter(x => x !== id); else arr.push(id);
  try { localStorage.setItem('rpg_thorns_named', JSON.stringify(arr)); } catch (e) {}
  renderThorns();
}

function thornEsc(s) { return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;"); }

function renderThorns() {
  const panel = document.getElementById('thorns-panel');
  if (!panel) return;
  try { thornsLang = (typeof lang !== 'undefined') ? lang : 'en'; } catch (e) {}
  const L = thornsS(thornsLang);
  const named = thornCount();
  const total = THORNS_LIST.length;

  const cards = THORNS_LIST.map(t => {
    /* t = [id, emoji, [en...], [es...], [fr...]] */
    const id = t[0], emoji = t[1];
    const li = thornsLang === 'es' ? 3 : thornsLang === 'fr' ? 4 : 2;
    const c = t[li] || t[2];
    const isOpen = thornNamed(id);
    return `<div style="background:var(--bg-card); border:1px solid ${isOpen ? 'var(--accent-green)' : 'var(--border-subtle)'}; border-radius:10px; margin-bottom:0.5rem; overflow:hidden;">
      <button onclick="thornToggle('${id}')" style="width:100%; text-align:left; background:transparent; border:none; color:var(--text-light); padding:0.65rem 0.8rem; cursor:pointer; font-family:inherit; font-size:0.9rem; display:flex; justify-content:space-between; align-items:center; gap:0.5rem;">
        <span style="font-weight:bold;">${emoji} ${thornEsc(c[0])} ${isOpen ? '<span style="color:var(--accent-green);">✓</span>' : ''}</span>
        <span style="color:var(--text-dim); font-size:0.75em; flex-shrink:0;">${isOpen ? '▲' : '▼'}</span>
      </button>
      ${isOpen ? `<div style="padding:0 0.8rem 0.8rem 0.8rem; font-size:0.85em; line-height:1.55;">
        <div style="color:var(--text-dim); margin-bottom:0.4rem;"><strong style="color:var(--accent-green);">${L.what}:</strong> ${thornEsc(c[1])}</div>
        <div style="color:var(--text-dim); margin-bottom:0.4rem;"><strong style="color:var(--accent-sand);">${L.shows}:</strong> ${thornEsc(c[2])}</div>
        <div style="background:var(--bg-input); border-left:3px solid var(--accent-gold); border-radius:6px; padding:0.5rem 0.7rem; margin-bottom:0.4rem; font-style:italic; color:var(--text-light);">${L.nameIt}: ${thornEsc(c[3])}</div>
        <div style="background:var(--bg-input); border-left:3px solid var(--accent-green); border-radius:6px; padding:0.5rem 0.7rem; margin-bottom:0.4rem; color:var(--text-light);">${L.meetIt}: ${thornEsc(c[4])}</div>
        <div style="font-size:0.78em; color:var(--accent-gold);">${L.voss}: <strong>${thornEsc(c[6])}</strong> — ${thornEsc(c[5])}</div>
      </div>` : ''}
    </div>`;
  }).join('');

  panel.innerHTML = `
    <div style="background:var(--bg-panel); border:1px solid var(--accent-gold); border-radius:12px; padding:1.1rem; margin-bottom:1rem;">
      <div style="display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:0.4rem; margin-bottom:0.4rem;">
        <h3 style="color:var(--accent-gold); margin:0;">🌹 ${thornEsc(L.title)}</h3>
        <span style="font-size:0.8em; color:var(--text-dim);">${L.progress}: <strong style="color:var(--accent-green);">${named}/${total}</strong></span>
      </div>
      <p style="font-size:0.88em; color:var(--text-light); margin-bottom:0.5rem;">${thornEsc(L.tag)}</p>
      <div style="background:var(--bg-input); border-left:3px solid var(--accent-gold); border-radius:6px; padding:0.6rem 0.8rem; margin-bottom:0.8rem; font-style:italic; color:var(--accent-gold);">${thornEsc(L.audit)}</div>
      ${cards}
      <div style="display:flex; gap:0.4rem; margin-top:0.8rem; flex-wrap:wrap;">
        <a class="btn btn-small" href="https://permies.com/wiki/123760/permaculture-thorns-Book-Build-Permaculture" target="_blank" style="text-decoration:none;">📖 ${thornEsc(L.book)}</a>
        <a class="btn btn-small" href="https://permies.com/wiki/380698/Podcast-Challenges-Building-Community-Part" target="_blank" style="text-decoration:none;">🎙️ ${thornEsc(L.podcast1)}</a>
        <a class="btn btn-small" href="https://permies.com/wiki/380877/Podcast-Challenges-Building-Community-Part" target="_blank" style="text-decoration:none;">🎙️ ${thornEsc(L.podcast2)}</a>
      </div>
    </div>`;
}

window.thornsLang = thornsLang;
window.renderThorns = renderThorns;
window.thornToggle = thornToggle;
window.thornNamed = thornNamed;
window.thornCount = thornCount;
window.THORNS_LIST = THORNS_LIST;
